<?php

namespace Database\Seeders;

use App\Models\PerangkatDaerah;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class PerangkatDaerahSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            // DINAS
            ['nama' => 'Dinas Komunikasi dan Informatika', 'slug' => 'diskominfo', 'email' => 'kominfo@malangkab.go.id', 'alamat' => 'Jl. K.H. Agus Salim No. 7 Malang 65119', 'telepon' => '0341364776'],
            ['nama' => 'Dinas Kependudukan dan Pencatatan Sipil', 'slug' => 'dispendukcapil', 'email' => 'dispendukcapil@malangkab.go.id', 'alamat' => 'Jl. Trunojoyo Kepanjen', 'telepon' => '0341399744'],
            ['nama' => 'Dinas Kesehatan', 'slug' => 'dinkes', 'email' => 'dinkes@malangkab.go.id', 'alamat' => 'JL PANJI 120 KEPANJEN', 'telepon' => '0341391621'],
            ['nama' => 'Dinas Ketahanan Pangan', 'slug' => 'dkp', 'email' => 'dkp.malangkab@gmail.com', 'alamat' => 'Jl. Raya Karangduren No. 1 Pakisaji - Malang', 'telepon' => '0341804423'],
            ['nama' => 'Dinas Koperasi dan Usaha Mikro', 'slug' => 'diskopum', 'email' => 'dinkop@malangkab.go.id', 'alamat' => 'Jl. Trunojoyo Kav. 1, Kepanjen', 'telepon' => '0341393921'],
            ['nama' => 'Dinas Lingkungan Hidup', 'slug' => 'dlh', 'email' => 'lh@malangkab.go.id', 'alamat' => 'Jl. Nusa Barong No. 13, Klojen, Malang', 'telepon' => '0341392029'],
            ['nama' => 'Dinas Pariwisata dan Kebudayaan', 'slug' => 'disparbud', 'email' => 'disparkabmalang@gmail.com', 'alamat' => 'Jl. KH. Agus Salim No. 7, Gedung J Lt.1 dan 2, Malang', 'telepon' => '082132091428'],
            ['nama' => 'Dinas Pekerjaan Umum Bina Marga', 'slug' => 'dpubm', 'email' => 'binamarga.kabmalang@gmail.com', 'alamat' => 'Jl. Trunojoyo Kavling 6 Kepanjen', 'telepon' => '0341393930'],
            ['nama' => 'Dinas Pekerjaan Umum Sumber Daya Air', 'slug' => 'dpusda', 'email' => 'sumberdayaair@malangkab.go.id', 'alamat' => 'Jl. Kawi No. 1, Kepanjen', 'telepon' => '0341395025'],
            ['nama' => 'Dinas Pemberdayaan Masyarakat dan Desa', 'slug' => 'dpmd', 'email' => 'dpmd@malangkab.go.id', 'alamat' => 'Jl. Merdeka Timur No. 3 Malang', 'telepon' => '0341352454'],
            ['nama' => 'Dinas Pemberdayaan Perempuan dan Perlindungan Anak', 'slug' => 'dpppa', 'email' => 'kpppamalang@gmail.com', 'alamat' => 'Jl. Jend. Ahmad Yani Utara No.384B, Arjosari', 'telepon' => '0341346682'],
            ['nama' => 'Dinas Pemuda dan Olahraga', 'slug' => 'dispora', 'email' => 'dispora@malangkab.go.id', 'alamat' => 'Jl. Trunojoyo Kompleks Stadion Kanjuruhan Kepanjen', 'telepon' => '0341399909'],
            ['nama' => 'Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu', 'slug' => 'dpmptsp', 'email' => 'pm-ptsp@malangkab.go.id', 'alamat' => 'Jl. Trunojoyo no. 4, Kedungpedaringan , Kepanjen', 'telepon' => '0341396633'],
            ['nama' => 'Dinas Pendidikan', 'slug' => 'disdik', 'email' => 'dispendik@malangkab.go.id', 'alamat' => 'Jl.Panarukan No. 1 Kepanjen', 'telepon' => '0341393935'],
            ['nama' => 'Dinas Pengendalian Penduduk dan Keluarga Berencana', 'slug' => 'dppkb', 'email' => 'dinas.kb@malangkab.go.id', 'alamat' => 'Jalan Raden Panji No. 158 Lantai 6 Kepanjen', 'telepon' => '03413905313'],
            ['nama' => 'Dinas Perhubungan', 'slug' => 'dishub', 'email' => 'dishub@malangkab.go.id', 'alamat' => 'Jl. Raya Talangagung, Kepanjen', 'telepon' => '03413901300'],
            ['nama' => 'Dinas Perikanan', 'slug' => 'diskan', 'email' => 'perikanankabmalang@gmail.com', 'alamat' => 'Jl. Panji No.119 Kepanjen Malang', 'telepon' => '0341399755'],
            ['nama' => 'Dinas Perindustrian dan Perdagangan', 'slug' => 'disperindag', 'email' => 'disperindag@malangkab.go.id', 'alamat' => 'Jl. PANJI No.119, Kepanjen', 'telepon' => '0341391676'],
            ['nama' => 'Dinas Perpustakaan dan Kearsipan', 'slug' => 'disperpusip', 'email' => 'perpus-arsip@malangkab.go.id', 'alamat' => 'Jalan Panglima Sudirman No.19 Kepanjen', 'telepon' => '0341397789'],
            ['nama' => 'Dinas Pertanahan', 'slug' => 'dispertan', 'email' => 'pertanahan@malangkab.go.id', 'alamat' => 'Gedung C Lantai 1, Jalan Merdeka Timur Nomor 3 Kota Malang', 'telepon' => '0341409001'],
            ['nama' => 'Dinas Perumahan, Kawasan Permukiman dan Cipta Karya', 'slug' => 'dpkpck', 'email' => 'perumahan-ciptakarya@malangkab.go.id', 'alamat' => 'Jl. Trunojoyo kapling 6 Kepanjen', 'telepon' => '0341391679'],
            ['nama' => 'Dinas Peternakan dan Kesehatan Hewan', 'slug' => 'disnakkeswan', 'email' => 'disnak-keswan@malangkab.go.id', 'alamat' => 'Jl. Trunojoyo Kav. 4 Kepanjen', 'telepon' => '0341393926'],
            ['nama' => 'Dinas Sosial', 'slug' => 'dinsos', 'email' => 'newdinsos@gmail.com', 'alamat' => 'Jl. Majapahit No.5 Malang', 'telepon' => '0341362601'],
            ['nama' => 'Dinas Tanaman Pangan, Hortikultura dan Perkebunan', 'slug' => 'dtphp', 'email' => 'dinas.tanaman.pangan@malangkab.go.id', 'alamat' => 'Jl.Sumedang No. 28 Kepanjen', 'telepon' => '0341396893'],
            ['nama' => 'Dinas Tenaga Kerja', 'slug' => 'disnaker', 'email' => 'disnaker@malangkab.go.id', 'alamat' => 'Jl.Trunojoyo Kav. 3 Kepanjen', 'telepon' => '0341393933'],

            // BADAN
            ['nama' => 'Badan Kepegawaian dan Pengembangan SDM', 'slug' => 'bkpsdm', 'email' => 'bkpsdm@malangkab.go.id', 'alamat' => 'Jl. KH.Agus Salim No.7 Malang', 'telepon' => '0341364776'],
            ['nama' => 'Badan Kesatuan Bangsa dan Politik', 'slug' => 'bakesbangpol', 'email' => 'bakesbangpol@malangkab.go.id', 'alamat' => 'Jl. Panji No. 158 Kepanjen', 'telepon' => '0341392031'],
            ['nama' => 'Badan Keuangan dan Aset Daerah', 'slug' => 'bkad', 'email' => 'bkad.malangkab@gmail.com', 'alamat' => 'Jl. KH.Agus Salim No.7 Malang', 'telepon' => '0341362372'],
            ['nama' => 'Badan Penanggulangan Bencana Daerah', 'slug' => 'bpbd', 'email' => 'bpbd@malangkab.go.id', 'alamat' => 'Jl. Trunojoyo Kepanjen', 'telepon' => '082244094886'],
            ['nama' => 'Badan Pendapatan Daerah', 'slug' => 'bapenda', 'email' => 'bapenda@malangkab.go.id', 'alamat' => 'Jl. Panji No.158 Kepanjen', 'telepon' => '03413904898'],
            ['nama' => 'Badan Perencanaan Pembangunan Daerah', 'slug' => 'bappeda', 'email' => 'bappeda@malangkab.go.id', 'alamat' => 'Jl. Panji No. 158 Kepanjen', 'telepon' => '0314392322'],
            ['nama' => 'Badan Riset dan Inovasi Daerah', 'slug' => 'brida', 'email' => 'brida@malangkab.go.id', 'alamat' => 'Jalan Panji Nomor 158 Kepanjen 65163', 'telepon' => '0341392023'],

            // KELURAHAN
            ['nama' => 'Kelurahan Ardirejo', 'slug' => 'kel-ardirejo', 'email' => 'kel-ardirejo@malangkab.go.id', 'alamat' => 'Jl. Ahmad Yani No. 162 Kepanjen', 'telepon' => '0341398244'],
            ['nama' => 'Kelurahan Candirenggo', 'slug' => 'kel-candirenggo', 'email' => 'kel-candirenggo@malangkab.go.id', 'alamat' => 'Jl. Kertanegara Barat No. 15 Singosari', 'telepon' => '0341458755'],
            ['nama' => 'Kelurahan Cepokomulyo', 'slug' => 'kel-cepokomulyo', 'email' => 'kel-cepokomulyo@malangkab.go.id', 'alamat' => 'Jl. Anggrek No. 31 Kepanjen', 'telepon' => '0341395595'],
            ['nama' => 'Kelurahan Dampit', 'slug' => 'kel-dampit', 'email' => 'kel-dampit@malangkab.go.id', 'alamat' => 'Jl. Semeru Selatan No 91 Dampit', 'telepon' => '0341896274'],
            ['nama' => 'Kelurahan Kalirejo', 'slug' => 'kel-kalirejo', 'email' => 'kel-kalirejo@malangkab.go.id', 'alamat' => 'JL. Sumber Taman No. 02 Kalirejo-Lawang', 'telepon' => '0341426398'],
            ['nama' => 'Kelurahan Kepanjen', 'slug' => 'kel-kepanjen', 'email' => 'kel-kepanjen@malangkab.go.id', 'alamat' => 'Jalan Sultan Agung No.2 Kepanjen', 'telepon' => '03417608883'],
            ['nama' => 'Kelurahan Lawang', 'slug' => 'kel-lawang', 'email' => 'kel-lawang@malangkab.go.id', 'alamat' => 'jl.sumbersuko No. 1 Lawang', 'telepon' => '0341426296'],
            ['nama' => 'Kelurahan Losari', 'slug' => 'kel-losari', 'email' => 'kel-losari@malangkab.go.id', 'alamat' => 'Jl. Suropati No. 157 Singosari', 'telepon' => '0341451002'],
            ['nama' => 'Kelurahan Pagentan', 'slug' => 'kel-pagentan', 'email' => 'pagentankelurahan@gmail.com', 'alamat' => 'Jl. Sidodadi No.20 Pagentan, Singosari', 'telepon' => '0341458251'],
            ['nama' => 'Kelurahan Penarukan', 'slug' => 'kel-penarukan', 'email' => 'kel-penarukan@malangkab.go.id', 'alamat' => 'Jl.Sultan Hasanudin No.17 Kepanjen', 'telepon' => '0341396150'],
            ['nama' => 'Kelurahan Sedayu', 'slug' => 'kel-sedayu', 'email' => 'kel-sedayu@malangkab.go.id', 'alamat' => 'Jl. Gatot Subroto No. 110 Turen', 'telepon' => '0341824311'],
            ['nama' => 'Kelurahan Turen', 'slug' => 'kel-turen', 'email' => 'kel-turen@malangkab.go.id', 'alamat' => 'Jl. Stadion Utara No. 02 Turen', 'telepon' => '0341824225'],

            // KECAMATAN
            ['nama' => 'Kecamatan Ampelgading', 'slug' => 'kec-ampelgading', 'email' => 'ampelgading@malangkab.go.id', 'alamat' => 'Jl. Raya Tirtomarto No.67 Ampelgading', 'telepon' => '851001'],
            ['nama' => 'Kecamatan Bantur', 'slug' => 'kec-bantur', 'email' => 'bantur@malangkab.go.id', 'alamat' => 'Jl. Raya Bantur No.1460 Bantur', 'telepon' => '841240'],
            ['nama' => 'Kecamatan Bululawang', 'slug' => 'kec-bululawang', 'email' => 'bululawang@malangkab.go.id', 'alamat' => 'Jl. Suropati Raya No.6 Bululawang', 'telepon' => '0341833131'],
            ['nama' => 'Kecamatan Dampit', 'slug' => 'kec-dampit', 'email' => 'KecamatanDampit86@gmail.com', 'alamat' => 'Jl. Semeru Selatan No.23 Dampit', 'telepon' => '0341896401'],
            ['nama' => 'Kecamatan Dau', 'slug' => 'kec-dau', 'email' => 'dau@malangkab.go.id', 'alamat' => 'Jl. Raya Mulyoagung No.200 Dau', 'telepon' => '462764'],
            ['nama' => 'Kecamatan Donomulyo', 'slug' => 'kec-donomulyo', 'email' => 'donomulyo@malangkab.go.id', 'alamat' => 'Jl. Raya Donomulyo No.62 Donomulyo', 'telepon' => '881009'],
            ['nama' => 'Kecamatan Gedangan', 'slug' => 'kec-gedangan', 'email' => 'kecamatangedangan160@gmail.com', 'alamat' => 'Jl. Raya Hasanudin No.160 Gedangan', 'telepon' => '087859930322'],
            ['nama' => 'Kecamatan Gondanglegi', 'slug' => 'kec-gondanglegi', 'email' => 'gondanglegi350710@gmail.com', 'alamat' => 'Jl. Diponegoro No 76 Gondanglegi', 'telepon' => '879209'],
            ['nama' => 'Kecamatan Jabung', 'slug' => 'kec-jabung', 'email' => 'jabung@malangkab.go.id', 'alamat' => 'Jl. Raya Sukolilo No. 1 Jabung', 'telepon' => '792132'],
            ['nama' => 'Kecamatan Kalipare', 'slug' => 'kec-kalipare', 'email' => 'kalipare@malangkab.go.id', 'alamat' => 'Jl. Raya Kalipare No.902 Kalipare', 'telepon' => '311234'],
            ['nama' => 'Kecamatan Karangploso', 'slug' => 'kec-karangploso', 'email' => 'karangploso@malangkab.go.id', 'alamat' => 'Jl. Diponegoro No.70 Karangploso', 'telepon' => '461626'],
            ['nama' => 'Kecamatan Kasembon', 'slug' => 'kec-kasembon', 'email' => 'kasembon@malangkab.go.id', 'alamat' => 'Jl. Raya Kasembon No 7 Kasembon', 'telepon' => '0354326418'],
            ['nama' => 'Kecamatan Kepanjen', 'slug' => 'kec-kepanjen', 'email' => 'kec.kepanjen@gmail.com', 'alamat' => 'Jl. Kawi No.50 Kepanjen', 'telepon' => '0341395006'],
            ['nama' => 'Kecamatan Kromengan', 'slug' => 'kec-kromengan', 'email' => 'kromengan@malangkab.go.id', 'alamat' => 'Jl. Nailun Selatan No.85 Kromengan', 'telepon' => '0822323201014'],
            ['nama' => 'Kecamatan Lawang', 'slug' => 'kec-lawang', 'email' => 'lawang@malangkab.go.id', 'alamat' => 'Jl. MH.Thamrin No.2 Lawang', 'telepon' => '0341426065'],
            ['nama' => 'Kecamatan Ngajum', 'slug' => 'kec-ngajum', 'email' => 'ngajum@malangkab.go.id', 'alamat' => 'JL. Ahmad Yani No.76 Ngajum', 'telepon' => '-'],
            ['nama' => 'Kecamatan Ngantang', 'slug' => 'kec-ngantang', 'email' => 'ngantang@malangkab.go.id', 'alamat' => 'Jl. Raya Ngantang No.25 Ngantang', 'telepon' => '521155'],
            ['nama' => 'Kecamatan Pagak', 'slug' => 'kec-pagak', 'email' => 'pagak@malangkab.go.id', 'alamat' => 'Jl. Abdul Razak No.1 Pagak', 'telepon' => '311123'],
            ['nama' => 'Kecamatan Pagelaran', 'slug' => 'kec-pagelaran', 'email' => 'pagelaran@malangkab.go.id', 'alamat' => 'Jl. Suropati No.54 Pagelaran', 'telepon' => '879429'],
            ['nama' => 'Kecamatan Pakis', 'slug' => 'kec-pakis', 'email' => 'kecamatanpakis.kabmalang@gmail.com', 'alamat' => 'Jl. Raya Pakis No.69 Pakis', 'telepon' => '791548'],
            ['nama' => 'Kecamatan Pakisaji', 'slug' => 'kec-pakisaji', 'email' => 'pakisaji@malangkab.go.id', 'alamat' => 'Jl. Pakisaji No.9 Pakisaji', 'telepon' => '801286'],
            ['nama' => 'Kecamatan Poncokusumo', 'slug' => 'kec-poncokusumo', 'email' => 'poncokusumo@malangkab.go.id', 'alamat' => 'Jl. Wonorejo No.4 Poncokusumo', 'telepon' => '787666'],
            ['nama' => 'Kecamatan Pujon', 'slug' => 'kec-pujon', 'email' => 'pujon@malangkab.go.id', 'alamat' => 'Jl. Brigjend Abdul Manan No.8 Pujon', 'telepon' => '524001'],
            ['nama' => 'Kecamatan Singosari', 'slug' => 'kec-singosari', 'email' => 'singosari@malangkab.go.id', 'alamat' => 'Jl. Tumapel No. 38 Singosari', 'telepon' => '0341458009'],
            ['nama' => 'Kecamatan Sumbermanjing Wetan', 'slug' => 'kec-sumbermanjing-wetan', 'email' => 'SumbermanjingWetan@malangkab.go.id', 'alamat' => 'Jl. Raya Argotirto No.88', 'telepon' => '871122'],
            ['nama' => 'Kecamatan Sumberpucung', 'slug' => 'kec-sumberpucung', 'email' => 'sumberpucungkecamatan@gmail.com', 'alamat' => 'Jl. Raya Ngebruk, Sumberpucung', 'telepon' => '385202'],
            ['nama' => 'Kecamatan Tajinan', 'slug' => 'kec-tajinan', 'email' => 'tajinan@malangkab.go.id', 'alamat' => 'Jl. Raya Tajinan Nomor 18', 'telepon' => '0341751287'],
            ['nama' => 'Kecamatan Tirtoyudo', 'slug' => 'kec-tirtoyudo', 'email' => 'tirtoyudo@malangkab.go.id', 'alamat' => 'Jl. Raya Tlogosari No.457 Tirtoyudo', 'telepon' => '8572003'],
            ['nama' => 'Kecamatan Tumpang', 'slug' => 'kec-tumpang', 'email' => 'tumpang@malangkab.go.id', 'alamat' => 'Jl. Raya Malangsuko 1A Tumpang', 'telepon' => '787211'],
            ['nama' => 'Kecamatan Turen', 'slug' => 'kec-turen', 'email' => 'turen@malangkab.go.id', 'alamat' => 'Jl. Panglima Sudirman No.102 Turen', 'telepon' => '0341824006'],
            ['nama' => 'Kecamatan Wagir', 'slug' => 'kec-wagir', 'email' => 'wagir@malangkab.go.id', 'alamat' => 'Jl. Raya Gondowangi No. 03 Wagir', 'telepon' => '804662'],
            ['nama' => 'Kecamatan Wajak', 'slug' => 'kec-wajak', 'email' => 'wajak@malangkab.go.id', 'alamat' => 'Jl. Panglima Sudirman No.96 Wajak', 'telepon' => '827759'],
            ['nama' => 'Kecamatan Wonosari', 'slug' => 'kec-wonosari', 'email' => 'wonosari@malangkab.go.id', 'alamat' => 'Jl. Raya Gunung Kawi No.10 Wonosari', 'telepon' => '370041'],

            // BAGIAN
            ['nama' => 'Bagian Administrasi Pembangunan', 'slug' => 'bag-pembangunan', 'email' => 'bag-ap@malangkab.go.id', 'alamat' => 'Gedung Sekretariat Daerah Lt 3 Jl. Panji No. 158 Kepanjen', 'telepon' => '0341392029'],
            ['nama' => 'Bagian Hukum', 'slug' => 'bag-hukum', 'email' => 'bag-hukum@malangkab.go.id', 'alamat' => 'Gedung Sekretariat Daerah Lt 4 Jl. Panji No. 158 Kepanjen', 'telepon' => '0341392029'],
            ['nama' => 'Bagian Kerja Sama', 'slug' => 'bag-kerjasama', 'email' => 'bag-kerjasama@malangkab.go.id', 'alamat' => 'Gedung Sekretariat Daerah Lt 4 Jl. Panji No. 158 Kepanjen', 'telepon' => '0341392029'],
            ['nama' => 'Bagian Kesejahteraan Rakyat', 'slug' => 'bag-kesra', 'email' => 'bag-kesra@malangkab.go.id', 'alamat' => 'Gedung Sekretariat Daerah Lt 4 Jl. Panji No. 158 Kepanjen', 'telepon' => '0341392029'],
            ['nama' => 'Bagian Organisasi', 'slug' => 'bag-organisasi', 'email' => 'bag-organisasi@malangkab.go.id', 'alamat' => 'Gedung Sekretariat Daerah Lt 3 Jl. Panji No. 158 Kepanjen', 'telepon' => '0341392029'],
            ['nama' => 'Bagian Pengadaan Barang/Jasa', 'slug' => 'bag-pbj', 'email' => 'bag-pbj@malangkab.go.id', 'alamat' => 'Gedung Sekretariat Daerah Lt 5 Jl. Panji No. 158 Kepanjen', 'telepon' => '0341392029'],
            ['nama' => 'Bagian Perekonomian', 'slug' => 'bag-ekonomi', 'email' => 'bag-ekonomi@malangkab.go.id', 'alamat' => 'Gedung Sekretariat Daerah Lt 5 Jl. Panji No. 158 Kepanjen', 'telepon' => '0341392029'],
            ['nama' => 'Bagian Perencanaan Dan Keuangan', 'slug' => 'bag-renkeu', 'email' => 'renkeu@malangkab.go.id', 'alamat' => 'Gedung Sekretariat Daerah Lt 3 Jl. Panji No. 158 Kepanjen', 'telepon' => '0341392029'],
            ['nama' => 'Bagian Protokol & Komunikasi Pimpinan', 'slug' => 'bag-prokopim', 'email' => 'bag-prokopim@malangkab.go.id', 'alamat' => 'Gedung Sekretariat Daerah Lt 1 Jl. Panji No. 158 Kepanjen', 'telepon' => '0341392440'],
            ['nama' => 'Bagian Sumber Daya Alam', 'slug' => 'bag-sda', 'email' => 'bag-sda@malangkab.go.id', 'alamat' => 'Gedung Sekretariat Daerah Lt 5 Jl. Panji No. 158 Kepanjen', 'telepon' => '085183132341'],
            ['nama' => 'Bagian Tata Pemerintahan', 'slug' => 'bag-tapem', 'email' => 'bag-tapem@malangkab.go.id', 'alamat' => 'Gedung Sekretariat Daerah Lt 4 Jl. Panji No. 158 Kepanjen', 'telepon' => '0341392025'],
            ['nama' => 'Bagian Umum', 'slug' => 'bag-umum', 'email' => 'bag-umum@malangkab.go.id', 'alamat' => 'Gedung Sekretariat Daerah Lt 1 Jl. Panji No. 158 Kepanjen', 'telepon' => '0341392029'],

            // --- ORGANISASI LAIN ---
            ['nama' => 'Badan Amil Zakat Nasional Kabupaten Malang', 'slug' => 'baznas-kab-malang', 'email' => null, 'alamat' => 'Jl. Trunojoyo, Ngadiluwih, Kedungpedaringan, Kec. Kepanjen, Malang, Jawa Timur 65163', 'telp' => '0341392489'],
            ['nama' => 'Dharma Wanita Persatuan Kabupaten Malang', 'slug' => 'dwp-kab-malang', 'email' => 'dharmawanita@malangkab.go.id', 'alamat' => 'Jl. K.H. Agus Salim 7', 'telp' => '0341326792'],
            ['nama' => 'DPRD Kabupaten Malang', 'slug' => 'dprd-kab-malang', 'email' => 'dprd@malangkab.go.id', 'alamat' => 'Jl. Panji No.119, Penarukan, Kec. Kepanjen, Malang, Jawa Timur 65163', 'telp' => '0341398400'],
            ['nama' => 'Inspektorat Daerah Kabupaten Malang', 'slug' => 'inspektorat', 'email' => 'inspektorat.malangkab@gmail.com', 'alamat' => 'JL. Raya Mondoroko No 17B Singosari - Malang', 'telp' => '0341451905'],
            ['nama' => 'KOMANDO DISTRIK MILITER 0818', 'slug' => 'kodim-0818', 'email' => null, 'alamat' => 'Malang', 'telp' => null],
            ['nama' => 'Pemberdayaan dan Kesejahteraan Keluarga', 'slug' => 'pkk-kab-malang', 'email' => 'tppkk.malangkab@gmail.com', 'alamat' => 'Jl. KH Agus Salim No.7 Malang', 'telp' => '0341364404'],
            ['nama' => 'Perumda JASA YASA', 'slug' => 'perumda-jasa-yasa', 'email' => 'Jasayasaofficial@gmail.com', 'alamat' => 'Jl. Basuki Rahmat 11 Kota Malang', 'telp' => '0341365411'],
            ['nama' => 'Perusahaan Umum Daerah Tirta Kanjuruhan', 'slug' => 'perumda-tirta-kanjuruhan', 'email' => 'humas@perumdatirtakanjuruhan.com', 'alamat' => 'Jl. Raya Kebonagung No.115 Pakisaji Malang', 'telp' => '0341801155'],
            ['nama' => 'PT BPR Artha Kanjuruhan Pemkab Malang', 'slug' => 'bpr-artha-kanjuruhan', 'email' => 'artha-kanjuruhan@malangkab.go.id', 'alamat' => 'Jl Raya Singosari 275 Singosari - Malang', 'telp' => '531334'],
            ['nama' => 'RSUD Kanjuruhan', 'slug' => 'rsud-kanjuruhan', 'email' => 'rsud-kanjuruhan@malangkab.go.id', 'alamat' => 'Jl. Panji 100, Kepanjen', 'telp' => '0341395041'],
            ['nama' => 'RSUD Lawang', 'slug' => 'rsud-lawang', 'email' => 'rsud-lawang@malangkab.go.id', 'alamat' => 'Jl. R.A Kartini No. 5 Lawang, Kabupaten Malang', 'telp' => '0341426072'],
            ['nama' => 'RSUD Ngantang', 'slug' => 'rsud-ngantang', 'email' => 'rsud-ngantang@malangkab.go.id', 'alamat' => 'Ngantang Kabupaten Malang', 'telp' => '0341'],
            ['nama' => 'Satgas COVID-19', 'slug' => 'satgas-covid-19', 'email' => 'satgascovid19@malangkab.go.id', 'alamat' => 'Kepanjen', 'telp' => '0341'],
            ['nama' => 'SATGAS MBG', 'slug' => 'satgas-mbg', 'email' => null, 'alamat' => 'Malang', 'telp' => null],
            ['nama' => 'Satuan Polisi Pamong Praja', 'slug' => 'satpol-pp', 'email' => 'satpolpp@malangkab.go.id', 'alamat' => 'Jl. Merdeka Timur N0.3 Malang', 'telp' => '0341350722'],
            ['nama' => 'SEKRETARIAT DAERAH', 'slug' => 'setda', 'email' => null, 'alamat' => 'Gedung Sekretariat Daerah', 'telp' => null],

            // --- UPT PUSKESMAS ---
            ['nama' => 'Puskesmas Ampelgading', 'slug' => 'puskesmas-ampelgading', 'email' => 'uptpuskesmasamgad@gmail.com', 'alamat' => 'Jl. Raya Tirtomarto No. 75, Ampelgading', 'telp' => '0341851076'],
            ['nama' => 'Puskesmas Ardimulyo', 'slug' => 'puskesmas-ardimulyo', 'email' => 'puskesmasardimulyo1@malangkab.go.id', 'alamat' => 'Malang', 'telp' => '0341458388'],
            ['nama' => 'Puskesmas Bantur', 'slug' => 'puskesmas-bantur', 'email' => 'puskesmasbantur@gmail.com', 'alamat' => 'Jl. Raya Bantur No. 2203 Kecamatan Bantur', 'telp' => '0341841113'],
            ['nama' => 'Puskesmas Dampit', 'slug' => 'puskesmas-dampit', 'email' => 'puskesmasdampit@malangkab.go.id', 'alamat' => 'Malang', 'telp' => '0341896309'],
            ['nama' => 'Puskesmas Dau', 'slug' => 'puskesmas-dau', 'email' => 'puskesmasdau212@gmail.com', 'alamat' => 'Jl. Raya Mulyoagung No. 212 Dau', 'telp' => '0341462123'],
            ['nama' => 'Puskesmas Donomulyo', 'slug' => 'puskesmas-donomulyo', 'email' => 'puskesmasdonomulyomalangkab@gmail.com', 'alamat' => 'Jl Raya Donomulyo No 343 Kecamatan Donomulyo', 'telp' => '0341881113'],
            ['nama' => 'Puskesmas Gedangan', 'slug' => 'puskesmas-gedangan', 'email' => 'puskesmasgedangan@malangkab.go.id', 'alamat' => 'Jl.Hasanudin 60 Gedangan-Malang', 'telp' => '081228866332'],
            ['nama' => 'Puskesmas Gondanglegi', 'slug' => 'puskesmas-gondanglegi', 'email' => 'puskesmasgondanglegi@malangkab.go.id', 'alamat' => 'Malang', 'telp' => '0341879223'],
            ['nama' => 'Puskesmas Jabung', 'slug' => 'puskesmas-jabung', 'email' => 'jabungpkm@gmail.com', 'alamat' => 'Malang', 'telp' => '0341793141'],
            ['nama' => 'Puskesmas Kalipare', 'slug' => 'puskesmas-kalipare', 'email' => 'puskesmaskalipare@malangkab.go.id', 'alamat' => 'Jl. Raya Kalipare No. 210 Kec. Kalipare', 'telp' => '0341311118'],
            ['nama' => 'Puskesmas Karangploso', 'slug' => 'puskesmas-karangploso', 'email' => 'puskesmaskarangploso@malangkab.go.id', 'alamat' => 'Malang', 'telp' => '0341461634'],
            ['nama' => 'Puskesmas Kasembon', 'slug' => 'puskesmas-kasembon', 'email' => 'puskesmaskasembon@malangkab.go.id', 'alamat' => 'Malang', 'telp' => '0341'],
            ['nama' => 'Puskesmas Kepanjen', 'slug' => 'puskesmas-kepanjen', 'email' => 'pkm_kepanjen@yahoo.co.id', 'alamat' => 'Jl. Raya Jatirejoyoso No. 04 Kepanjen', 'telp' => '03413903007'],
            ['nama' => 'Puskesmas Ketawang', 'slug' => 'puskesmas-ketawang', 'email' => 'puskesmasketawang@malangkab.go.id', 'alamat' => 'Jalan Raya Ketawang No.13, Gondanglegi', 'telp' => '0341879009'],
            ['nama' => 'Puskesmas Kromengan', 'slug' => 'puskesmas-kromengan', 'email' => 'puskesmaskromengan@gmail.com', 'alamat' => 'Jln. Nailun Utara No 104 Karangrejo Kec. Kromengan', 'telp' => '03414342036'],
            ['nama' => 'Puskesmas Lawang', 'slug' => 'puskesmas-lawang', 'email' => 'puskesmaslawang@malangkab.go.id', 'alamat' => 'Malang', 'telp' => '0341423189'],
            ['nama' => 'Puskesmas Ngajum', 'slug' => 'puskesmas-ngajum', 'email' => 'puskesmasngajum@malangkab.go.id', 'alamat' => 'Jl. A.Yani No.22 Ngajum', 'telp' => '0341398100'],
            ['nama' => 'Puskesmas Ngantang', 'slug' => 'puskesmas-ngantang', 'email' => 'puskesmasngantang@malangkab.go.id', 'alamat' => 'Malang', 'telp' => '0341'],
            ['nama' => 'Puskesmas Pagak', 'slug' => 'puskesmas-pagak', 'email' => 'puskesmaspagak@gmai.com', 'alamat' => 'Malang', 'telp' => '0341311002'],
            ['nama' => 'Puskesmas Pagelaran', 'slug' => 'puskesmas-pagelaran', 'email' => 'pkm-pagelaran@malangkab.go.id', 'alamat' => 'Malang', 'telp' => '0341875262'],
            ['nama' => 'Puskesmas Pakis', 'slug' => 'puskesmas-pakis', 'email' => 'puskesmaspakis@malangkab.go.id', 'alamat' => 'Jl. Raya Pakis Kembar No 70, Pakis', 'telp' => '0341791549'],
            ['nama' => 'Puskesmas Pakisaji', 'slug' => 'puskesmas-pakisaji', 'email' => 'puskesmaspakisaji@malangkab.go.id', 'alamat' => 'Jln Raya Pakisaji No.19 Malang', 'telp' => '0341802932'],
            ['nama' => 'Puskesmas Pamotan', 'slug' => 'puskesmas-pamotan', 'email' => 'puskesmaspamotan@malangkab.go.id', 'alamat' => 'Jl. Ahmad Yani No.68 Pamotan Kec. Dampit', 'telp' => '03418591117'],
            ['nama' => 'Puskesmas Poncokusumo', 'slug' => 'puskesmas-poncokusumo', 'email' => 'pkmponcokusumo@gmail.com', 'alamat' => 'Jl. Kusnan Marzuki No. 101, Desa Wonomulyo', 'telp' => '03412319509'],
            ['nama' => 'Puskesmas Pujon', 'slug' => 'puskesmas-pujon', 'email' => 'puskesmaspujon259@gmail.com', 'alamat' => 'Jl.Brigjend Abdul Manan Wijaya No.259 Desa Pujon Lor', 'telp' => '0341524046'],
            ['nama' => 'Puskesmas Singosari', 'slug' => 'puskesmas-singosari', 'email' => 'puskesmassingosari@malangkab.go.id', 'alamat' => 'Jl. Tohjoyo III Singosari', 'telp' => '0341458961'],
            ['nama' => 'Puskesmas Sitiarjo', 'slug' => 'puskesmas-sitiarjo', 'email' => 'puskesmassitiarjo@malangkab.go.id', 'alamat' => 'Malang', 'telp' => '0341'],
            ['nama' => 'Puskesmas Sumawe', 'slug' => 'puskesmas-sumawe', 'email' => 'puskesmassumawe@malangkab.go.id', 'alamat' => 'Malang', 'telp' => '0341871141'],
            ['nama' => 'Puskesmas Sumbermanjing Kulon', 'slug' => 'puskesmas-sumbermanjing-kulon', 'email' => 'pkmsumakul@gmail.com', 'alamat' => 'JL. Ahmad Yani No. 27 Sumbermanjing Kulon', 'telp' => '0341881199'],
            ['nama' => 'Puskesmas Sumberpucung', 'slug' => 'puskesmas-sumberpucung', 'email' => 'puskesmassumberpucung@malangkab.go.id', 'alamat' => 'Jl. TGP 02 Sumberpucung', 'telp' => '085792748644'],
            ['nama' => 'Puskesmas Tajinan', 'slug' => 'puskesmas-tajinan', 'email' => 'puskesmastajinan@malangkab.go.id', 'alamat' => 'Malang', 'telp' => '0341751380'],
            ['nama' => 'Puskesmas Tirtoyudo', 'slug' => 'puskesmas-tirtoyudo', 'email' => 'puskesmastirtoyudo@malangkab.go.id', 'alamat' => 'Jl. Samudera No. 66 Tirtoyudo', 'telp' => '03418591025'],
            ['nama' => 'Puskesmas Tumpang', 'slug' => 'puskesmas-tumpang', 'email' => 'puskesmastumpang@malangkab.go.id', 'alamat' => 'Malang', 'telp' => '0341'],
            ['nama' => 'Puskesmas Turen', 'slug' => 'puskesmas-turen', 'email' => 'puskesmasturen@gmail.go.id', 'alamat' => 'Jl. Panglima sudirman No 210 Turen', 'telp' => '0341824214'],
            ['nama' => 'Puskesmas Wagir', 'slug' => 'puskesmas-wagir', 'email' => 'puskesmaswagir@malangkab.go.id', 'alamat' => 'Jalan Raya Pandanrejo No.61 Kecamatan Wagir', 'telp' => '0341834666'],
            ['nama' => 'Puskesmas Wajak', 'slug' => 'puskesmas-wajak', 'email' => 'puskesmaswajak@malangkab.go.id', 'alamat' => 'Jl. Panglima Sudirman No. 161, Kec. Wajak', 'telp' => '0341824804'],
            ['nama' => 'Puskesmas Wonokerto', 'slug' => 'puskesmas-wonokerto', 'email' => 'puskesmaswonokerto@malangkab.go.id', 'alamat' => 'Malang', 'telp' => '0341'],
            ['nama' => 'Puskesmas Wonosari', 'slug' => 'puskesmas-wonosari', 'email' => 'puskesmaswonosari@malangkab.go.id', 'alamat' => 'JL. RAYA BUMIREJO NO 84 KEBOBANG', 'telp' => '0341370114'],
            ['nama' => 'UPT Laboratorium Kesehatan', 'slug' => 'upt-labkes', 'email' => 'uptlabkeskabmalang@gmail.com', 'alamat' => 'Jl. Panji No. 120 Kepanjen', 'telp' => '0341391621'],
            ['nama' => 'UPT PENGUJIAN DAN KALIBRASI ALAT KESEHATAN', 'slug' => 'upt-pkak', 'email' => 'kalibrasikabmalang@gmail.com', 'alamat' => 'Jl. Panji No. 120 Kepanjen', 'telp' => '081357354500'],
            ['nama' => 'UPT Puskesmas Bululawang', 'slug' => 'puskesmas-bululawang', 'email' => 'puskesmasbululawang13@gmail.com', 'alamat' => 'Jl. Stasiun No. 11-13, Kec. Bululawang', 'telp' => '085126460818'],

            // --- DESA BAGIAN 1 ---
            ['nama' => 'Ardimulyo', 'slug' => 'ardimulyo', 'email' => 'desaardimulyo@gmail.com', 'alamat' => 'Jl Diponegoro No 65', 'telp' => '+6281331205875'],
            ['nama' => 'Amadanom', 'slug' => 'amadanom', 'email' => 'desa-amadanom@malangkab.go.id', 'alamat' => 'Amadanom', 'telp' => '0341'],
            ['nama' => 'Ampeldento (Karangploso)', 'slug' => 'ampeldento-karangploso', 'email' => 'desa-ampeldento-karangploso@malangkab.go.id', 'alamat' => 'Ampeldento', 'telp' => '0341'],
            ['nama' => 'Ampeldento (Pakis)', 'slug' => 'ampeldento-pakis', 'email' => 'desa-ampeldento-pakis@malangkab.go.id', 'alamat' => 'Ampeldento', 'telp' => '0341'],
            ['nama' => 'Ampelgading', 'slug' => 'ampelgading', 'email' => 'desa-ampelgading@malangkab.go.id', 'alamat' => 'Ampelgading', 'telp' => '0341'],
            ['nama' => 'Argosari', 'slug' => 'argosari', 'email' => 'desa-argosari@malangkab.go.id', 'alamat' => 'Argosari', 'telp' => '0341'],
            ['nama' => 'Argosuko', 'slug' => 'argosuko', 'email' => 'desa-argosuko@malangkab.go.id', 'alamat' => 'Argosuko', 'telp' => '0341'],
            ['nama' => 'Argotirto', 'slug' => 'argotirto', 'email' => 'desa-argotirto@malangkab.go.id', 'alamat' => 'Argotirto', 'telp' => '0341'],
            ['nama' => 'Argoyuwono', 'slug' => 'argoyuwono', 'email' => 'desa-argoyuwono@malangkab.go.id', 'alamat' => 'Argoyuwono', 'telp' => '0'],
            ['nama' => 'Arjosari', 'slug' => 'arjosari', 'email' => 'desa-arjosari@malangkab.go.id', 'alamat' => 'Arjosari', 'telp' => '0341'],
            ['nama' => 'Arjowilangun', 'slug' => 'arjowilangun', 'email' => 'desa-arjowilangun@malangkab.go.id', 'alamat' => 'Jl. Diponegoro No 1 Barisan', 'telp' => '65166'],
            ['nama' => 'Asrikaton', 'slug' => 'asrikaton', 'email' => 'desa-asrikaton@malangkab.go.id', 'alamat' => 'Asrikaton', 'telp' => '0341'],
            ['nama' => 'Babadan', 'slug' => 'babadan', 'email' => 'desa-babadan@malangkab.go.id', 'alamat' => 'Babadan', 'telp' => '0341'],
            ['nama' => 'Bakalan', 'slug' => 'bakalan', 'email' => 'desa-bakalan@malangkab.go.id', 'alamat' => 'Jl Raya Bakalan Desa Bakalan Kec. Bululawang', 'telp' => '0341'],
            ['nama' => 'Balearjo', 'slug' => 'balearjo', 'email' => 'desa-balearjo@malangkab.go.id', 'alamat' => 'Balearjo', 'telp' => '0341'],
            ['nama' => 'Balesari', 'slug' => 'balesari', 'email' => 'desa-balesari@malangkab.go.id', 'alamat' => 'Balesari', 'telp' => '0341'],
            ['nama' => 'Bambang', 'slug' => 'bambang', 'email' => 'desa-bambang@malangkab.go.id', 'alamat' => 'Bambang', 'telp' => '0341'],
            ['nama' => 'Bandung Rejo', 'slug' => 'bandung-rejo', 'email' => 'desa-bandungrejo@malangkab.go.id', 'alamat' => 'Bandung Rejo', 'telp' => '0341'],
            ['nama' => 'Bangelan', 'slug' => 'bangelan', 'email' => 'desa-bangelan@malangkab.go.id', 'alamat' => 'Bangelan', 'telp' => '0341'],
            ['nama' => 'Banjararum', 'slug' => 'banjararum', 'email' => 'desa-banjararum@malangkab.go.id', 'alamat' => 'Jl Raya Karanglo no. 38', 'telp' => '0341441744'],
            ['nama' => 'Banjarejo (Donomulyo)', 'slug' => 'banjarejo-donomulyo', 'email' => 'desa-banjarejo-donomulyo@malangkab.go.id', 'alamat' => 'Dusun Krajan Rt 10 Rw 03 Desa Banjarejo', 'telp' => '0341'],
            ['nama' => 'Banjarejo (Ngantang)', 'slug' => 'banjarejo-ngantang', 'email' => 'desa-banjarejo-ngantang@malangkab.go.id', 'alamat' => 'Banjarejo', 'telp' => '0341'],
            ['nama' => 'Banjarejo (Pagelaran)', 'slug' => 'banjarejo-pagelaran', 'email' => 'desa-banjarejo-pagelaran@malangkab.go.id', 'alamat' => 'Banjarejo', 'telp' => '0341'],
            ['nama' => 'Banjarejo (Pakis)', 'slug' => 'banjarejo-pakis', 'email' => 'desa-banjarejo-pakis@malangkab.go.id', 'alamat' => 'Banjarejo', 'telp' => '0341'],
            ['nama' => 'Banjarsari', 'slug' => 'banjarsari', 'email' => 'desa-banjarsari@malangkab.go.id', 'alamat' => 'Banjarsari', 'telp' => '0341'],
            ['nama' => 'Bantur', 'slug' => 'bantur', 'email' => 'desa-bantur@malangkab.go.id', 'alamat' => 'Bantur', 'telp' => '0341'],
            ['nama' => 'Banturejo', 'slug' => 'banturejo', 'email' => 'info@desabanturejo.id', 'alamat' => 'Jl. Raya Banturejo No 06', 'telp' => '03415230053'],
            ['nama' => 'Baturetno (Dampit)', 'slug' => 'baturetno-dampit', 'email' => 'desa-baturetno-dampit.malangkab.go.id', 'alamat' => 'Baturetno', 'telp' => '0341'],
            ['nama' => 'Baturetno (Singosari)', 'slug' => 'baturetno-singosari', 'email' => 'desa-baturetno-singosari@malangkab.go.id', 'alamat' => 'Baturetno', 'telp' => '0341'],
            ['nama' => 'Bayem', 'slug' => 'bayem', 'email' => 'desa-bayemm@malangkab.go.id', 'alamat' => 'Bayem', 'telp' => '0341'],
            ['nama' => 'Bedali', 'slug' => 'bedali', 'email' => 'desa-bedali@gmail.com', 'alamat' => 'Jalan DR.Cipto No. 65 Lawang', 'telp' => '0341428611'],
            ['nama' => 'Belung', 'slug' => 'belung', 'email' => 'desa-belung@malangkab.go.id', 'alamat' => 'Belung', 'telp' => '0341'],
            ['nama' => 'Bendosari', 'slug' => 'bendosari', 'email' => 'desa-bendosari@malangkab.go.id', 'alamat' => 'Bendosari', 'telp' => '0341'],
            ['nama' => 'Benjor', 'slug' => 'benjor', 'email' => 'desa-benjor@malangkab.go.id', 'alamat' => 'Benjor', 'telp' => '0341'],
            ['nama' => 'Blayu', 'slug' => 'blayu', 'email' => 'desa-blayu@malangkab.go.id', 'alamat' => 'Blayu', 'telp' => '0341'],
            ['nama' => 'Bocek', 'slug' => 'bocek', 'email' => 'desa-bocek@malangkab.go.id', 'alamat' => 'Bocek', 'telp' => '0341'],
            ['nama' => 'Bokor', 'slug' => 'bokor', 'email' => 'desa-bokor.malangkab.go.id', 'alamat' => 'Bokor', 'telp' => '0341'],
            ['nama' => 'Bringin', 'slug' => 'bringin', 'email' => 'desa-bringin@malangkab.go.id', 'alamat' => 'Bringin', 'telp' => '0341'],
            ['nama' => 'Brongkal', 'slug' => 'brongkal', 'email' => 'desa-brongkal@malangkab.go.id', 'alamat' => 'Brongkal', 'telp' => '0341'],
            ['nama' => 'Bululawang', 'slug' => 'bululawang', 'email' => 'desa-bululawang@malangkab.go.id', 'alamat' => 'Bululawang', 'telp' => '0341'],
            ['nama' => 'Bulupitu', 'slug' => 'bulupitu', 'email' => 'desa-bulupitu@malangkab.go.id', 'alamat' => 'Jl. Pertahanan No.06, Krajan, Bulupitu', 'telp' => '03417982253'],
            ['nama' => 'Bumirejo', 'slug' => 'bumirejo', 'email' => 'desa-bumirejo@malangkab.go.id', 'alamat' => 'Bumirejo', 'telp' => '0341'],
            ['nama' => 'Bunut Wetan', 'slug' => 'bunut-wetan', 'email' => 'desabunutwetan@gmail.com', 'alamat' => 'Bunut Wetan', 'telp' => '0341'],

            // --- DESA BAGIAN 2 ---
            ['nama' => 'Clumprit', 'slug' => 'clumprit', 'email' => 'desa-clumprit@malangkab.go.id', 'alamat' => 'Clumprit', 'telp' => '0341'],
            ['nama' => 'Codo', 'slug' => 'codo', 'email' => 'desa-codo@malangkab.go.id', 'alamat' => 'Codo', 'telp' => '0341'],
            ['nama' => 'Curungrejo', 'slug' => 'curungrejo', 'email' => 'desa-curungrejo@malangkab.go.id', 'alamat' => 'Curungrejo', 'telp' => '0341'],
            ['nama' => 'Dadapan', 'slug' => 'dadapan', 'email' => 'desa-dadapan@malangkab.go.id', 'alamat' => 'Dadapan', 'telp' => '0341'],
            ['nama' => 'Dalisodo', 'slug' => 'dalisodo', 'email' => 'desa-dalisodo@malangkab.go.id', 'alamat' => 'Dalisodo', 'telp' => '0341'],
            ['nama' => 'Dawuhan', 'slug' => 'dawuhan', 'email' => 'desa-dawuhan@malangkab.go.id', 'alamat' => 'Dawuhan', 'telp' => '0341'],
            ['nama' => 'Dengkol', 'slug' => 'dengkol', 'email' => 'desa-dengkol@malangkab.go.id', 'alamat' => 'Dengkol', 'telp' => '0341454518'],
            ['nama' => 'Desa Karangduren', 'slug' => 'desa-karangduren', 'email' => 'desa-karangduren@malangkab.go.id', 'alamat' => 'Karangduren', 'telp' => '0341'],
            ['nama' => 'Desa Lebakharjo', 'slug' => 'desa-lebakharjo', 'email' => 'lebakharjo@malangkab.go.id', 'alamat' => 'Jalan Penggalang Nomor 71', 'telp' => '0341'],
            ['nama' => 'DESA NGADIREJO KECAMATAN KROMENGAN', 'slug' => 'desa-ngadirejo-kromengan', 'email' => 'desa-ngadirejo-kromengan@malangkab.go.id', 'alamat' => 'Ngadirejo', 'telp' => '0341384119'],
            ['nama' => 'Desa Pamotan Kecamatan Dampit', 'slug' => 'desa-pamotan-dampit', 'email' => 'desa-pamotan@malangkab.go.id', 'alamat' => 'Jalan Jendral Ahmad Yani No.292', 'telp' => '03418591489'],
            ['nama' => 'DESA SEMPALWADAK', 'slug' => 'desa-sempalwadak', 'email' => 'desa-sempalwadak@malangkab.go.id', 'alamat' => 'JL RAYA SEMPALWADAK NO 47', 'telp' => '0341807982'],
            ['nama' => 'Desa Sukodono', 'slug' => 'desa-sukodono', 'email' => 'desa-sukodono@malangkab.go.id', 'alamat' => 'Jl. Raya Sawur No. 01 Desa Sukodono', 'telp' => '0341'],
            ['nama' => 'Dilem', 'slug' => 'dilem', 'email' => 'desa-dilem@malangkab.go.id', 'alamat' => 'Dilem', 'telp' => '0341'],
            ['nama' => 'Donomulyo', 'slug' => 'donomulyo', 'email' => 'desa-donomulyo@malangkab.go.id', 'alamat' => 'Donomulyo', 'telp' => '0341'],
            ['nama' => 'Donowarih', 'slug' => 'donowarih', 'email' => 'desa-donowarih@malangkab.go.id', 'alamat' => 'Donowarih', 'telp' => '0341'],
            ['nama' => 'Druju', 'slug' => 'druju', 'email' => 'desa-druju@malangkab.go.id', 'alamat' => 'Druju', 'telp' => '0341'],
            ['nama' => 'Duwet', 'slug' => 'duwet', 'email' => 'desa-duwet@malangkab.go.id', 'alamat' => 'Duwet', 'telp' => '0341'],
            ['nama' => 'Duwet Krajan', 'slug' => 'duwet-krajan', 'email' => 'desa-duwetkrajan@malangkab.go.id', 'alamat' => 'Duwet Krajan', 'telp' => '0341'],
            ['nama' => 'Gading', 'slug' => 'gading', 'email' => 'desa-gading@malangkab.go.id', 'alamat' => 'Gading', 'telp' => '0341'],
            ['nama' => 'Gading Kembar', 'slug' => 'gading-kembar', 'email' => 'desa-gadingkembar@malangkab.go.id', 'alamat' => 'Gading Kembar', 'telp' => '0341'],
            ['nama' => 'Gadingkulon', 'slug' => 'gadingkulon', 'email' => 'desa-gadingkulon@malangkab.go.id', 'alamat' => 'Gadingkulon', 'telp' => '0341'],
            ['nama' => 'Gadungsari', 'slug' => 'gadungsari', 'email' => 'desa-gandusari@malangkab.go.id', 'alamat' => 'Gadungsari', 'telp' => '0341'],
            ['nama' => 'Gajahrejo', 'slug' => 'gajahrejo', 'email' => 'desa-gajahrejo@malangkab.go.id', 'alamat' => 'Gajahrejo', 'telp' => '0341'],
            ['nama' => 'Gampingan', 'slug' => 'gampingan', 'email' => 'desagampinganpagak@gmai.com', 'alamat' => 'Jl Raya No.73 Gampingan', 'telp' => '0341398679'],
            ['nama' => 'Ganjaran', 'slug' => 'ganjaran', 'email' => 'desa-ganjaran@malangkab.go.id', 'alamat' => 'Ganjaran', 'telp' => '0341'],
            ['nama' => 'Gedangan', 'slug' => 'gedangan', 'email' => 'desa-gedangan@malangkab.go.id', 'alamat' => 'Gedangan', 'telp' => '0341'],
            ['nama' => 'Gedog Kulon', 'slug' => 'gedog-kulon', 'email' => 'desa-gedogkulon@malangkab.go.id', 'alamat' => 'Gedog Kulon', 'telp' => '0341'],
            ['nama' => 'Gedog Wetan', 'slug' => 'gedog-wetan', 'email' => 'desa-gedogwetan@malangkab.go.id', 'alamat' => 'Gedog Wetan', 'telp' => '0341'],
            ['nama' => 'Genengan', 'slug' => 'genengan', 'email' => 'desa-genengan@malangkab.go.id', 'alamat' => 'Genengan', 'telp' => '0341'],
            ['nama' => 'Girimoyo', 'slug' => 'girimoyo', 'email' => 'desa-girimoyo@malangkab.go.id', 'alamat' => 'Girimoyo', 'telp' => '0341'],
            ['nama' => 'Girimulyo', 'slug' => 'girimulyo', 'email' => 'desa-girimulyo@malangkab.go.id', 'alamat' => 'Girimulyo', 'telp' => '0341'],
            ['nama' => 'Glanggang', 'slug' => 'glanggang', 'email' => 'desa-glanggang@malangkab.go.id', 'alamat' => 'Glanggang', 'telp' => '0341'],
            ['nama' => 'Gondanglegi Kulon', 'slug' => 'gondanglegi-kulon', 'email' => 'desa-gondanglegikulon@malangkab.go.id', 'alamat' => 'Gondanglegi Kulon', 'telp' => '0341'],
            ['nama' => 'Gondanglegi Wetan', 'slug' => 'gondanglegi-wetan', 'email' => 'desa-gondanglegiwetan@malangkab.go.id', 'alamat' => 'Gondanglegi Wetan', 'telp' => '0341'],
            ['nama' => 'Gondowangi', 'slug' => 'gondowangi', 'email' => 'desa-gondowangi@malangkab.go.id', 'alamat' => 'Gondowangi', 'telp' => '0341'],
            ['nama' => 'Gubugklakah', 'slug' => 'gubugklakah', 'email' => 'desa-gubugklakah@malangkab.go.id', 'alamat' => 'Gubugklakah', 'telp' => '0341'],
            ['nama' => 'Gunungjati', 'slug' => 'gunungjati', 'email' => 'desa-gunungjati@malangkab.go.id', 'alamat' => 'Gunungjati', 'telp' => '0341'],
            ['nama' => 'Gunungronggo', 'slug' => 'gunungronggo', 'email' => 'desa-gunungronggo@malangkab.go.id', 'alamat' => 'Gunungronggo', 'telp' => '0341'],
            ['nama' => 'Gunungsari', 'slug' => 'gunungsari', 'email' => 'desa-gunungsari@malangkab.go.id', 'alamat' => 'Gunungsari', 'telp' => '0341800156'],

            // --- DESA BAGIAN 3 ---
            ['nama' => 'Harjokuncaran', 'slug' => 'harjokuncaran', 'email' => 'desa-harjokuncaran@malangkab.go.id', 'alamat' => 'Harjokuncaran', 'telp' => '0341'],
            ['nama' => 'Jabung', 'slug' => 'jabung', 'email' => 'desa-jabung@malangkab.go.id', 'alamat' => 'Jabung', 'telp' => '0341'],
            ['nama' => 'Jambangan', 'slug' => 'jambangan', 'email' => 'desa-jambangan@malangkab.go.id', 'alamat' => 'Jambangan', 'telp' => '0341'],
            ['nama' => 'Jambearjo', 'slug' => 'jambearjo', 'email' => 'pemdesjambearjo@gmail.com', 'alamat' => 'Jambearjo', 'telp' => '081230385200'],
            ['nama' => 'Jambesari', 'slug' => 'jambesari', 'email' => 'desa-jambesari@malangkab.go.id', 'alamat' => 'Jambesari', 'telp' => '0341'],
            ['nama' => 'Jambuwer', 'slug' => 'jambuwer', 'email' => 'desa-jambuwer@malangkab.go.id', 'alamat' => 'Jl. Raya Desa Jambuwer No 577', 'telp' => '0341'],
            ['nama' => 'Jatiguwi', 'slug' => 'jatiguwi', 'email' => 'desa-jatiguwi@malangkab.go.id', 'alamat' => 'Jatiguwi', 'telp' => '0341'],
            ['nama' => 'Jatikerto', 'slug' => 'jatikerto', 'email' => 'desa-jatikerto@malangkab.go.id', 'alamat' => 'Jatikerto', 'telp' => '0341'],
            ['nama' => 'Jatirejoyoso', 'slug' => 'jatirejoyoso', 'email' => 'desa-jatirejoyoso@malangkab.go.id', 'alamat' => 'Jatirejoyoso', 'telp' => '0341'],
            ['nama' => 'Jatisari', 'slug' => 'jatisari-pakisaji', 'email' => 'desa-jatisari-pakisaji@malangkab.go.id', 'alamat' => 'Jatisari', 'telp' => '0341'],
            ['nama' => 'Jatisari Tajinan', 'slug' => 'jatisari-tajinan', 'email' => 'pemdesjatisari02@gmail.com', 'alamat' => 'Jl.KH.Salim Nomor 01', 'telp' => '0341'],
            ['nama' => 'Jedong', 'slug' => 'jedong', 'email' => 'desa-jedong@malangkab.go.id', 'alamat' => 'Jedong', 'telp' => '0341'],
            ['nama' => 'Jenggolo', 'slug' => 'jenggolo', 'email' => 'desa-jenggolo@malangkab.go.id', 'alamat' => 'Jenggolo', 'telp' => '0341'],
            ['nama' => 'Jeru', 'slug' => 'jeru-tumpang', 'email' => 'desa-jeru-tumpang@malangkab.go.id', 'alamat' => 'Jeru', 'telp' => '0341'],
            ['nama' => 'Jeru', 'slug' => 'jeru-turen', 'email' => 'desa-jeru-turen@malangkab.go.id', 'alamat' => 'Jeru', 'telp' => '0341'],
            ['nama' => 'Jogomulyan', 'slug' => 'jogomulyan', 'email' => 'desa-jogomulyan@malangkab.go.id', 'alamat' => 'Jogomulyan', 'telp' => '0341'],
            ['nama' => 'Jombok', 'slug' => 'jombok', 'email' => 'desa-jombok-ngantang@malangkab.go.id', 'alamat' => 'Jombok', 'telp' => '0341'],
            ['nama' => 'Kademangan', 'slug' => 'kademangan', 'email' => 'desa-kademangan@malangkab.go.id', 'alamat' => 'Kademangan', 'telp' => '0341'],
            ['nama' => 'Kaliasri', 'slug' => 'kaliasri', 'email' => 'desa-kaliasri@malangkab.go.id', 'alamat' => 'Jl. Raya Kaliasri No.29', 'telp' => '0341'],
            ['nama' => 'Kalipare', 'slug' => 'kalipare', 'email' => 'desa-kalipare@malangkab.go.id', 'alamat' => 'Kalipare', 'telp' => '0341'],
            ['nama' => 'Kalirejo', 'slug' => 'kalirejo', 'email' => 'desa-kalirejo@malangkab.go.id', 'alamat' => 'Kalirejo', 'telp' => '0341'],
            ['nama' => 'Kalisongo', 'slug' => 'kalisongo', 'email' => 'desa-kalisongo@malangkab.go.id', 'alamat' => 'Kalisongo', 'telp' => '0341'],
            ['nama' => 'Kambingan', 'slug' => 'kambingan', 'email' => 'desa-kambingan@malangkab.go.id', 'alamat' => 'Kambingan', 'telp' => '0341'],
            ['nama' => 'Kanigoro', 'slug' => 'kanigoro', 'email' => 'desa-kanigoro@malangkab.go.id', 'alamat' => 'Kanigoro', 'telp' => '0341'],
            ['nama' => 'Karangayar', 'slug' => 'karangayar', 'email' => 'desa-karangayar@malangkab.go.id', 'alamat' => 'Karangayar', 'telp' => '0341'],
            ['nama' => 'Karangkates', 'slug' => 'karangkates', 'email' => 'desa-karangkates2malangkab.go.id', 'alamat' => 'Karangkates', 'telp' => '0341383881'],
            ['nama' => 'Karangnongko', 'slug' => 'karangnongko', 'email' => 'desakrnongko@gmail.com', 'alamat' => 'Jl.Raya Karangnongko', 'telp' => '082242386861'],
            ['nama' => 'Karangpandan', 'slug' => 'karangpandan', 'email' => 'desa-karangpandan@malangkab.go.id', 'alamat' => 'Karangpandan', 'telp' => '0341'],

            // --- DESA BAGIAN 4 ---
            ['nama' => 'Karangrejo', 'slug' => 'karangrejo', 'email' => 'desa-karangrejo@malangkab.go.id', 'alamat' => 'Karangrejo', 'telp' => '0341'],
            ['nama' => 'Karangsari', 'slug' => 'karangsari', 'email' => 'desa-karangsari@malangkab.go.id', 'alamat' => 'Karangsari', 'telp' => '0341'],
            ['nama' => 'Karangsuko', 'slug' => 'karangsuko', 'email' => 'desa-karangsuko@malangkab.go.id', 'alamat' => 'Karangsuko', 'telp' => '0341'],
            ['nama' => 'Karangwidoro', 'slug' => 'karangwidoro', 'email' => 'desa-karangwidoro@malangkab.go.id', 'alamat' => 'Karangwidoro', 'telp' => '0341'],
            ['nama' => 'Kasembon', 'slug' => 'kasembon-bululawang', 'email' => 'desa-kasembon-bululawang@malangkab.go.id', 'alamat' => 'Kasembon', 'telp' => '0341'],
            ['nama' => 'Kasembon', 'slug' => 'kasembon', 'email' => 'desa-kasembon@malangkab.go.id', 'alamat' => 'Kasembon', 'telp' => '0341'],
            ['nama' => 'Kasri', 'slug' => 'kasri', 'email' => 'desa-kasri@malangkab.go.id', 'alamat' => 'Kasri', 'telp' => '0341'],
            ['nama' => 'Kaumrejo', 'slug' => 'kaumrejo', 'email' => 'desa-kaumrejo@malangkab.go.id', 'alamat' => 'Jl. Rambutan 26 Dusun Prabon I', 'telp' => '0341'],
            ['nama' => 'Kebobang', 'slug' => 'kebobang', 'email' => 'desa-kebobang@malangkab.go.id', 'alamat' => 'Kebobang', 'telp' => '0341'],
            ['nama' => 'Kebonagung', 'slug' => 'kebonagung', 'email' => 'desa-kebonagung@malangkab.go.id', 'alamat' => 'Kebonagung', 'telp' => '0341'],
            ['nama' => 'Kedok', 'slug' => 'kedok', 'email' => 'desa-kedok@malangkab.go.id', 'alamat' => 'Kedok', 'telp' => '0341'],
            ['nama' => 'Kedung Pendaringan', 'slug' => 'kedung-pendaringan', 'email' => 'desa-kedungpendaringan@malangkab.go.id', 'alamat' => 'Kedung Pendaringan', 'telp' => '0341'],
            ['nama' => 'Kedungbanteng', 'slug' => 'kedungbanteng', 'email' => 'desa-kedungbanteng@malangkab.go.id', 'alamat' => 'Kedungbanteng', 'telp' => '0341'],
            ['nama' => 'Kedungrejo', 'slug' => 'kedungrejo', 'email' => 'desa-kedungrejo@malangkab.go.id', 'alamat' => 'Kedungrejo', 'telp' => '0341'],
            ['nama' => 'Kedungsalam', 'slug' => 'kedungsalam', 'email' => 'desa-kedungsalam@malangkab.go.id', 'alamat' => 'Kedungsalam', 'telp' => '0341'],
            ['nama' => 'Kemantren', 'slug' => 'kemantren', 'email' => 'desa-kemantren@malangkab.go.id', 'alamat' => 'Kemantren', 'telp' => '0341'],
            ['nama' => 'Kemiri', 'slug' => 'kemiri-jabung', 'email' => 'desa-kemiri-jabung@malangkab.go.id', 'alamat' => 'Kemiri', 'telp' => '0341'],
            ['nama' => 'Kemiri', 'slug' => 'kemiri-kepanjen', 'email' => 'desa-kemiri-kepanjen@malangkab.go.id', 'alamat' => 'Kemiri', 'telp' => '0341'],
            ['nama' => 'Kemulan', 'slug' => 'kemulan', 'email' => 'desa-kemulan@malangkab.go.id', 'alamat' => 'Kemulan', 'telp' => '0341'],
            ['nama' => 'Kendalpayak', 'slug' => 'kendalpayak', 'email' => 'desa-kendalpayak@malangkab.go.id', 'alamat' => 'Kendalpayak', 'telp' => '0341'],
            ['nama' => 'Kenongo', 'slug' => 'kenongo', 'email' => 'kenongo.jabung@gmail.com', 'alamat' => 'Kenongo', 'telp' => '0341'],
            ['nama' => 'Kepatihan', 'slug' => 'kepatihan', 'email' => 'desa-kepatihan@malangkab.go.id', 'alamat' => 'Kepatihan', 'telp' => '0341'],
            ['nama' => 'Kepuharjo', 'slug' => 'kepuharjo', 'email' => 'desa-kepuharjo@malangkab.go.id', 'alamat' => 'Kepuharjo', 'telp' => '0341532021'],
            ['nama' => 'Kesamben', 'slug' => 'kesamben', 'email' => 'desa-kesamben@malangkab.go.id', 'alamat' => 'Kesamben', 'telp' => '0341'],
            ['nama' => 'Ketawang', 'slug' => 'ketawang', 'email' => 'desa-ketawang@malangkab.go.id', 'alamat' => 'Ketawang', 'telp' => '0341'],
            ['nama' => 'Ketindan', 'slug' => 'ketindan', 'email' => 'desa-ketindan@malangkab.go.id', 'alamat' => 'Ketindan', 'telp' => '0341'],
            ['nama' => 'Kidal', 'slug' => 'kidal', 'email' => 'desa-kidal@malangkab.go.id', 'alamat' => 'Kidal', 'telp' => '0341'],
            ['nama' => 'Kidangbangg', 'slug' => 'kidangbangg', 'email' => 'desa-kidangbang@malangkab.go.id', 'alamat' => 'Kidangbanggs', 'telp' => '0341'],
            ['nama' => 'Klampok', 'slug' => 'klampok', 'email' => 'desa-klampok@malangkab.go.id', 'alamat' => 'Klampok', 'telp' => '0341'],
            ['nama' => 'Klepu', 'slug' => 'klepu', 'email' => 'desa-klepu@malangkab.go.id', 'alamat' => 'Klepu', 'telp' => '0341'],
            ['nama' => 'Kluwut', 'slug' => 'kluwut', 'email' => 'desa-kluwut@malangkab.go.id', 'alamat' => 'Kluwut', 'telp' => '0341'],
            ['nama' => 'Kranggan', 'slug' => 'kranggan', 'email' => 'desa-kranggan@malangkab.go.id', 'alamat' => 'Kranggan', 'telp' => '0341'],
            ['nama' => 'Krebet', 'slug' => 'krebet', 'email' => 'desa-krebet@malangkab.go.id', 'alamat' => 'Krebet', 'telp' => '0341'],
            ['nama' => 'Krebet Senggrong', 'slug' => 'krebet-senggrong', 'email' => 'desa-krebetsenggrong@malangkab.go.id', 'alamat' => 'Krebet Senggrong', 'telp' => '0341'],
            ['nama' => 'Kromengan', 'slug' => 'kromengan', 'email' => 'desa-kromengan@malangkab.go.id', 'alamat' => 'Kromengan', 'telp' => '0341'],
            ['nama' => 'Kucur', 'slug' => 'kucur', 'email' => 'desa-kucur@malangkab.go.id', 'alamat' => 'Kucur', 'telp' => '0341'],
            ['nama' => 'Kuwolu', 'slug' => 'kuwolu', 'email' => 'kuwolualmaqbul@gmail.com', 'alamat' => 'Kuwolu', 'telp' => '0341'],
            ['nama' => 'Landungsari', 'slug' => 'landungsari', 'email' => 'desa-landungsari@malangkab.go.id', 'alamat' => 'Landungsari', 'telp' => '0341'],
            ['nama' => 'Lang-lang', 'slug' => 'lang-lang', 'email' => 'pemdeslanglang@gmail.com', 'alamat' => 'Jln. Langlang Rejo RT 12 RW 01', 'telp' => '0341'],
            ['nama' => 'Lumbangsari', 'slug' => 'lumbangsari', 'email' => 'desa-lumbangsari@malangkab.go.id', 'alamat' => 'Lumbangsari', 'telp' => '0341'],

            // --- DESA BAGIAN 5 ---
            ['nama' => 'Madiredo', 'slug' => 'madiredo', 'email' => 'desa-madiredo@malangkab.go.id', 'alamat' => 'Madiredo', 'telp' => '0341'],
            ['nama' => 'Maguan', 'slug' => 'maguan', 'email' => 'pemdesmaguan@gmail.com', 'alamat' => 'Jl. Ir. Soekarno No. 21 Maguan', 'telp' => '081336182835'],
            ['nama' => 'Majangtengah', 'slug' => 'majangtengah', 'email' => 'desa-majangtengah@malangkab.go.id', 'alamat' => 'Majangtengah', 'telp' => '0341'],
            ['nama' => 'Malangsuko', 'slug' => 'malangsuko', 'email' => 'desa-malangsuko@malangkab.go.id', 'alamat' => 'Malangsuko', 'telp' => '0341'],
            ['nama' => 'Mangliawan', 'slug' => 'mangliawan', 'email' => 'desa-mangliawan@malangkab.go.id', 'alamat' => 'Mangliawan', 'telp' => '0341'],
            ['nama' => 'Mangunrejo', 'slug' => 'mangunrejo', 'email' => 'desa-mangunrejo@malangkab.go.id', 'alamat' => 'Mangunrejo', 'telp' => '0341'],
            ['nama' => 'Mendalanwangi', 'slug' => 'mendalanwangi', 'email' => 'desa-mendalanwangi@malangkab.go.id', 'alamat' => 'Mendalanwangi', 'telp' => '0341'],
            ['nama' => 'Mentaram', 'slug' => 'mentaram', 'email' => 'desa-mentaram@malangkab.go.id', 'alamat' => 'Mentaram', 'telp' => '5471865'],
            ['nama' => 'Mojosari', 'slug' => 'mojosari', 'email' => 'desa-mojosari@malangkab.go.id', 'alamat' => 'Mojosari', 'telp' => '0341'],
            ['nama' => 'Mulyoagung', 'slug' => 'mulyoagung', 'email' => 'desa-mulyoagung@malangkab.go.id', 'alamat' => 'Mulyoagung', 'telp' => '0341'],
            ['nama' => 'Mulyoarjo', 'slug' => 'mulyoarjo', 'email' => 'desa-mulyoarjo@malangkab.go.id', 'alamat' => 'Mulyoarjo', 'telp' => '0341'],
            ['nama' => 'Mulyoasri', 'slug' => 'mulyoasri', 'email' => 'desa-mulyoasri@malangkab.go.id', 'alamat' => 'Mulyoasri', 'telp' => '0341'],
            ['nama' => 'Mulyorejo', 'slug' => 'mulyorejo', 'email' => 'dsmulyorejongantang@gmail.com', 'alamat' => 'Mulyorejo', 'telp' => '0341'],
            ['nama' => 'Ngabab', 'slug' => 'ngabab', 'email' => 'desa-ngabab@malangkab.go.id', 'alamat' => 'Ngabab', 'telp' => '0341'],
            ['nama' => 'Ngadas', 'slug' => 'ngadas', 'email' => 'desa-ngadas@malangkab.go.id', 'alamat' => 'Ngadas', 'telp' => '0341'],
            ['nama' => 'Ngadilangkung', 'slug' => 'ngadilangkung', 'email' => 'desa-ngadilangkung@malangkab.go.id', 'alamat' => 'Ngadilangkung', 'telp' => '0341'],
            ['nama' => 'Ngadirejo', 'slug' => 'ngadirejo-jabung', 'email' => 'desa-ngadirejo-jabung@malangkab.go.id', 'alamat' => 'Ngadirejo', 'telp' => '0341'],
            ['nama' => 'Ngadireso', 'slug' => 'ngadireso', 'email' => 'desa-ngadireso@malangkab.go.id', 'alamat' => 'Ngadireso', 'telp' => '0341'],
            ['nama' => 'Ngajum', 'slug' => 'ngajum', 'email' => 'desa-ngajum@malangkab.go.id', 'alamat' => 'Ngajum', 'telp' => '0341'],
            ['nama' => 'Ngantru', 'slug' => 'ngantru', 'email' => 'desa-ngantru@malangkab.go.id', 'alamat' => 'Ngantru', 'telp' => '0341'],
            ['nama' => 'Ngasem', 'slug' => 'ngasem', 'email' => 'desa-ngasem@malangkab.go.id', 'alamat' => 'Ngasem', 'telp' => '0341'],
            ['nama' => 'Ngawonggo', 'slug' => 'ngawonggo', 'email' => 'desa-ngawonggo@malangkab.go.id', 'alamat' => 'Ngawonggo', 'telp' => '085233797757'],
            ['nama' => 'Ngebruk', 'slug' => 'ngebruk-poncokusumo', 'email' => 'desa-ngebruk-poncokusumo@malangkab.go.id', 'alamat' => 'Ngebruk', 'telp' => '0341'],
            ['nama' => 'Ngebruk', 'slug' => 'ngebruk-sumberpucung', 'email' => 'desa-ngebruk-sumberpucung@malangkab.go.id', 'alamat' => 'Ngebruk', 'telp' => '0341'],
            ['nama' => 'Ngembal', 'slug' => 'ngembal', 'email' => 'desa-ngembal@malangkab.go.id', 'alamat' => 'Ngembal', 'telp' => '0341'],
            ['nama' => 'Ngenep', 'slug' => 'ngenep', 'email' => 'desa-ngenep@malangkab.go.id', 'alamat' => 'Ngenep', 'telp' => '0341'],
            ['nama' => 'Ngijo', 'slug' => 'ngijo', 'email' => 'desa-ngijo@malangkab.go.id', 'alamat' => 'Ngijo', 'telp' => '0341'],
            ['nama' => 'Ngingit', 'slug' => 'ngingit', 'email' => 'desa-ngingit@malangkab.go.id', 'alamat' => 'Ngingit', 'telp' => '0341'],
            ['nama' => 'Ngroto', 'slug' => 'ngroto', 'email' => 'desa-ngroto@malangkab.go.id', 'alamat' => 'Ngroto', 'telp' => '0341'],
            ['nama' => 'Pagak', 'slug' => 'pagak', 'email' => 'desa-pagak@malangkab.go.id', 'alamat' => 'Pagak', 'telp' => '0341'],
            ['nama' => 'Pagedangan', 'slug' => 'pagedangan', 'email' => 'desa-pagedangan@malangkab.go.id', 'alamat' => 'Pagedangan', 'telp' => '0341'],
            ['nama' => 'Pagelaran', 'slug' => 'pagelaran', 'email' => 'desa-pagelaran@malangkab.go.id', 'alamat' => 'Pagelaran', 'telp' => '0341'],
            ['nama' => 'Pagersari', 'slug' => 'pagersari', 'email' => 'desa-pagersari@malangkab.go.id', 'alamat' => 'Pagersari', 'telp' => '0341'],
            ['nama' => 'Pait', 'slug' => 'pait', 'email' => 'desa-pait@malangkab.go.id', 'alamat' => 'Pait', 'telp' => '0341'],
            ['nama' => 'Pajaran', 'slug' => 'pajaran', 'email' => 'desa-pajaran@malangkab.go.id', 'alamat' => 'Pajaran', 'telp' => '0341'],
            ['nama' => 'Pakisaji', 'slug' => 'pakisaji', 'email' => 'desapakisaji@gmail.com', 'alamat' => 'Pakisaji', 'telp' => '08885250702'],
            ['nama' => 'Pakisjajar', 'slug' => 'pakisjajar', 'email' => 'desa-pakisjajar@malangkab.go.id', 'alamat' => 'Pakisjajar', 'telp' => '0341'],
            ['nama' => 'Pakiskembar', 'slug' => 'pakiskembar', 'email' => 'desa-pakiskembar@malangkab.go.id', 'alamat' => 'Pakiskembar', 'telp' => '0341'],
            ['nama' => 'Palaan', 'slug' => 'palaan', 'email' => 'desa-palaan@malangkab.go.id', 'alamat' => 'Palaan', 'telp' => '0341'],
            ['nama' => 'Pandanajeng', 'slug' => 'pandanajeng', 'email' => 'desa-pandanajeng@malangkab.go.id', 'alamat' => 'Pandanajeng', 'telp' => '0341'],
            ['nama' => 'Pandanlandung', 'slug' => 'pandanlandung', 'email' => 'desa-pandanlandung@malangkab.go.id', 'alamat' => 'Pandanlandung', 'telp' => '0341'],
            ['nama' => 'Pandanmulyo', 'slug' => 'pandanmulyo', 'email' => 'desa-pandanmulyo@malangkab.go.id', 'alamat' => 'Pandanmulyo', 'telp' => '0341'],
            ['nama' => 'Pandanrejo', 'slug' => 'pandanrejo-pagak', 'email' => 'desa-pandanrejo-pagak@malangkab.go.id', 'alamat' => 'Pandanrejo', 'telp' => '0341'],
            ['nama' => 'Pandanrejo', 'slug' => 'pandanrejo-wagir', 'email' => 'desa-pandanrejo-wagir@malangkab.go.id', 'alamat' => 'Pandanrejo', 'telp' => '0341'],
            ['nama' => 'Pandansari', 'slug' => 'pandansari-ngantang', 'email' => 'desa-pandansari-ngantang@malangkab.go.id', 'alamat' => 'Pandansari', 'telp' => '0341'],
            ['nama' => 'Pandansari', 'slug' => 'pandansari', 'email' => 'pemdes.pandansari.k@gmail.com', 'alamat' => 'Pandansari', 'telp' => '0341'],
            ['nama' => 'Pandansari Lor', 'slug' => 'pandansari-lor', 'email' => 'desa-pandansari lor@malangkab.go.id', 'alamat' => 'Pandansari Lor', 'telp' => '0341'],
            ['nama' => 'Pandesari', 'slug' => 'pandesari', 'email' => 'pemdespandesari@gmail.com', 'alamat' => 'Jl. Brigjen Abd. Manan Wijaya No. 40', 'telp' => '0341513290'],

            // --- DESA BAGIAN 6 ---
            ['nama' => 'Panggungrejo', 'slug' => 'panggungrejo-gondanglegi', 'email' => 'desa-panggungrejo-gondanglegi@malangkab.go.id', 'alamat' => 'Panggungrejo', 'telp' => '0341'],
            ['nama' => 'Panggungrejo', 'slug' => 'panggungrejo-kepanjen', 'email' => 'desa-panggungrejo-kepanjen@malangkab.go.id', 'alamat' => 'Panggungrejo', 'telp' => '0341'],
            ['nama' => 'Parangargo', 'slug' => 'parangargo', 'email' => 'desa-parangargo@malangkab.go.id', 'alamat' => 'Parangargo', 'telp' => '0341'],
            ['nama' => 'Patokpicis', 'slug' => 'patokpicis', 'email' => 'desa-patokpicis@malangkab.go.id', 'alamat' => 'Patokpicis', 'telp' => '0341'],
            ['nama' => 'Pemerintah Desa Gunungrejo', 'slug' => 'gunungrejo', 'email' => 'desa-gunungrejo@malangkab.go.id', 'alamat' => 'Desa Gunungrejo', 'telp' => '0341'],
            ['nama' => 'Pemerintah Desa Toyomarto', 'slug' => 'toyomarto', 'email' => 'desatoyomarto1@gmail.com', 'alamat' => 'Jl Raya Bodean Krajan No. 329', 'telp' => '451914'],
            ['nama' => 'Peniwen', 'slug' => 'peniwen', 'email' => 'desa-peniwen@malangkab.go.id', 'alamat' => 'Peniwen', 'telp' => '03417662987'],
            ['nama' => 'Permanu', 'slug' => 'permanu', 'email' => 'pemdespermanu35071901@gmail.com', 'alamat' => 'Jl. Raya Permanu No. 50', 'telp' => '0341'],
            ['nama' => 'Petungsewu', 'slug' => 'petungsewu-dau', 'email' => 'desa-petungsewu-dau@malangkab.go.id', 'alamat' => 'Petungsewu', 'telp' => '0341'],
            ['nama' => 'Petungsewu', 'slug' => 'petungsewu-wagir', 'email' => 'desa-petungsewu-wagir@malangkab.go.id', 'alamat' => 'Petungsewu', 'telp' => '0341'],
            ['nama' => 'Plandi', 'slug' => 'plandi', 'email' => 'desa-plandi@malangkab.go.id', 'alamat' => 'Plandi', 'telp' => '0341'],
            ['nama' => 'Plaosan', 'slug' => 'plaosan', 'email' => 'desa-plaosan@malangkab.go.id', 'alamat' => 'Plaosan', 'telp' => '0341'],
            ['nama' => 'Pojok', 'slug' => 'pojok', 'email' => 'desa-pojok@malangkab.go.id', 'alamat' => 'Pojok', 'telp' => '0341'],
            ['nama' => 'Poncokusumo', 'slug' => 'poncokusumo', 'email' => 'desa-poncokusumo@malangkab.go.id', 'alamat' => 'Poncokusumo', 'telp' => '0341'],
            ['nama' => 'Pondokagung', 'slug' => 'pondokagung', 'email' => 'desa-pondokagung@malangkab.go.id', 'alamat' => 'Pondokagung', 'telp' => '0341'],
            ['nama' => 'Pringgodani', 'slug' => 'pringgodani', 'email' => 'desa-pringgodani@malangkab.go.id', 'alamat' => 'Pringgodani', 'telp' => '0341'],
            ['nama' => 'Pringu', 'slug' => 'pringu', 'email' => 'desa-pringu@malangkab.go.id', 'alamat' => 'Jl. Raya Panglima Sudirman No. 111', 'telp' => '0341823511'],
            ['nama' => 'Pucangsongo', 'slug' => 'pucangsongo', 'email' => 'desa-pucangsongo@malangkab.go.id', 'alamat' => 'Pucangsongo', 'telp' => '0341'],
            ['nama' => 'Pujiharjo', 'slug' => 'pujiharjo', 'email' => 'desa-pujiharjo@malangkab.go.id', 'alamat' => 'Pujiharjo', 'telp' => '0341'],
            ['nama' => 'Pujon Kidul', 'slug' => 'pujon-kidul', 'email' => 'desa-pujonkidul@malangkab.go.id', 'alamat' => 'Pujon Kidul', 'telp' => '0341'],
            ['nama' => 'Pujon Lor', 'slug' => 'pujon-lor', 'email' => 'desa-pujonlor@malangkab.go.id', 'alamat' => 'Pujon Lor', 'telp' => '0341'],
            ['nama' => 'Pulungdowo', 'slug' => 'pulungdowo', 'email' => 'desa-pulungdowo@malangkab.go.id', 'alamat' => 'Pulungdowo', 'telp' => '0341'],
            ['nama' => 'Purwoasri', 'slug' => 'purwoasri', 'email' => 'desa-purwoasri@malangkab.go.id', 'alamat' => 'Purwoasri', 'telp' => '0341'],
            ['nama' => 'Purwodadi', 'slug' => 'purwodadi-donomulyo', 'email' => 'desa-purwodadi-donomulyo@malangkab.go.id', 'alamat' => 'Jalan Lawu No 01', 'telp' => '081217778025'],
            ['nama' => 'Purwodadi', 'slug' => 'purwodadi-tirtoyudo', 'email' => 'desa-purwodadi-tirtoyudo@malangkab.go.id', 'alamat' => 'Dusun Purwodadi', 'telp' => '085791983060'],
            ['nama' => 'Purwoharjo', 'slug' => 'purwoharjo', 'email' => 'desa-purwoharjo@malangkab.go.id', 'alamat' => 'Purwoharjo', 'telp' => '0341'],
            ['nama' => 'Purworejo', 'slug' => 'purworejo-donomulyo', 'email' => 'desa-purworejo-donomulyo@malangkab.go.id', 'alamat' => 'Purworejo', 'telp' => '0341'],
            ['nama' => 'Purworejo', 'slug' => 'purworejo-ngantang', 'email' => 'desa-purworejo-ngantang@malangkab.go.id', 'alamat' => 'Purworejo', 'telp' => '0341'],
            ['nama' => 'Purwosekar', 'slug' => 'purwosekar', 'email' => 'desa-purwosekar.malangkab.go.id', 'alamat' => 'Purwosekar', 'telp' => '0341'],
            ['nama' => 'Putat Kidul', 'slug' => 'putat-kidul', 'email' => 'desa-putatkidul@malangkab.go.id', 'alamat' => 'Putat Kidul', 'telp' => '0341'],
            ['nama' => 'Putat lor', 'slug' => 'putat-lor', 'email' => 'desa-putatlor@malangkab.go.id', 'alamat' => 'Putat lordesa', 'telp' => '0341'],
            ['nama' => 'Putukrejo', 'slug' => 'putukrejo-gondanglegi', 'email' => 'desa-putukrejo-gondanglegi@malangkab.go.id', 'alamat' => 'Putukrejo', 'telp' => '0341'],
            ['nama' => 'Putukrejo', 'slug' => 'putukrejo-kalipare', 'email' => 'desa-putukrejo-kalipare@malangkab.go.id', 'alamat' => 'Putukrejo', 'telp' => '0341'],
            ['nama' => 'Randuagung', 'slug' => 'randuagung', 'email' => 'desa-randuagung@malangkab.go.id', 'alamat' => 'Randuagung', 'telp' => '0341'],
            ['nama' => 'Randugading', 'slug' => 'randugading', 'email' => 'desa-randugading@malangkab.go.id', 'alamat' => 'Randugading', 'telp' => '0341'],
            ['nama' => 'REJOSARI', 'slug' => 'rejosari', 'email' => 'desa-rejosari@malangkab.go.id', 'alamat' => 'Jl.Raya Rejosari No.78', 'telp' => '0341'],
            ['nama' => 'Rejoyoso', 'slug' => 'rejoyoso', 'email' => 'desa-rejoyoso@malangkab.go.id', 'alamat' => 'Rejoyoso', 'telp' => '6571682'],
            ['nama' => 'Rembun', 'slug' => 'rembun', 'email' => 'desa-rembun@malangkab.go.id', 'alamat' => 'Rembun', 'telp' => '0341'],
            ['nama' => 'Ringinkembar', 'slug' => 'ringinkembar', 'email' => 'desa-ringinkembar@malangkab.go.id', 'alamat' => 'Ringinkembar', 'telp' => '0341'],
            ['nama' => 'Ringinsari', 'slug' => 'ringinsari', 'email' => 'desa-ringinsari@malangkab.go.id', 'alamat' => 'Raya Ringinsari No. 44', 'telp' => '081295567778'],
            ['nama' => 'Sambigede', 'slug' => 'sambigede', 'email' => 'desa-sambigede@malangkab.go.id', 'alamat' => 'Sambigede', 'telp' => '0341'],
            ['nama' => 'Sanan Kerto', 'slug' => 'sanan-kerto', 'email' => 'desa-sanankerto@malangkab.go.id', 'alamat' => 'Sanan Kerto', 'telp' => '0341'],
            ['nama' => 'Sananrejo', 'slug' => 'sananrejo', 'email' => 'desa-sananrejo@malangkab.go.id', 'alamat' => 'Jl. Soekarno Hatta No. 1', 'telp' => '03418521513'],
            ['nama' => 'Saptorenggo', 'slug' => 'saptorenggo', 'email' => 'desa-saptorenggo@malangkab.go.id', 'alamat' => 'Saptorenggo', 'telp' => '0341'],
            ['nama' => 'Sawahan', 'slug' => 'sawahan', 'email' => 'desa-sawahan@malangkab.go.id', 'alamat' => 'Sawahan', 'telp' => '0341'],
            ['nama' => 'Segaran', 'slug' => 'segaran', 'email' => 'desa-segaran@malangkab.go.id', 'alamat' => 'Segaran', 'telp' => '0341'],
            ['nama' => 'Sekarbanyu', 'slug' => 'sekarbanyu', 'email' => 'desa-sekarbanyu@malangkab.go.id', 'alamat' => 'Sekarbanyu', 'telp' => '0341'],
            ['nama' => 'Sekarpuro', 'slug' => 'sekarpuro', 'email' => 'desa-sekarpuro@malangkab.go.id', 'alamat' => 'Sekarpuro', 'telp' => '0341'],
            ['nama' => 'Selorejo', 'slug' => 'selorejo', 'email' => 'desa-selorejo@malangkab.go.id', 'alamat' => 'Selorejo', 'telp' => '0341'],
            ['nama' => 'Sempol', 'slug' => 'sempol', 'email' => 'desa-sempol@malangkab.go.id', 'alamat' => 'Sempol', 'telp' => '0341'],
            ['nama' => 'Senggreng', 'slug' => 'senggreng', 'email' => 'desa-senggreng@malangkab.go.id', 'alamat' => 'Senggreng', 'telp' => '0341'],
            ['nama' => 'Sengguruh', 'slug' => 'sengguruh', 'email' => 'desa-sengguruh@malangkab.go.id', 'alamat' => 'Sengguruh', 'telp' => '0341'],

            // --- DESA BAGIAN 7 ---
            ['nama' => 'Sepanjang', 'slug' => 'sepanjang', 'email' => 'desa-sepanjang@malangkab.go.id', 'alamat' => 'Sepanjang', 'telp' => '0341'],
            ['nama' => 'Sidoasri', 'slug' => 'sidoasri', 'email' => 'desa-sidoasri@malangkab.go.id', 'alamat' => 'Sidoasri', 'telp' => '0341'],
            ['nama' => 'Sidodadi', 'slug' => 'sidodadi-gedangan', 'email' => 'desa-sidodadi-gedangan@malangkab.go.id', 'alamat' => 'Sidodadi', 'telp' => '0341'],
            ['nama' => 'Sidodadi', 'slug' => 'sidodadi-lawang', 'email' => 'desa-sidodadi-lawang@malangkab.go.id', 'alamat' => 'Sidodadi', 'telp' => '0341'],
            ['nama' => 'Sidodadi', 'slug' => 'sidodadi-ngantang', 'email' => 'desa-sidodadi-ngantang@malangkab.go.id', 'alamat' => 'Sidodadi', 'telp' => '0341'],
            ['nama' => 'Sidoluhur', 'slug' => 'sidoluhur', 'email' => 'desa-sidoluhur@malangkab.go.id', 'alamat' => 'Sidoluhur', 'telp' => '0341'],
            ['nama' => 'Sidomulyo', 'slug' => 'sidomulyo', 'email' => 'desa-sidomulyo.malangkab.go.id', 'alamat' => 'Sidomulyo', 'telp' => '081217038959'],
            ['nama' => 'Sidorahayu', 'slug' => 'sidorahayu', 'email' => 'desa-sidorahayu@malangkab.go.id', 'alamat' => 'Sidorahayu', 'telp' => '0341'],
            ['nama' => 'Sidorejo', 'slug' => 'sidorejo-jabung', 'email' => 'desa-sidorejo-jabung@malangkab.go.id', 'alamat' => 'Sidorejo', 'telp' => '0341'],
            ['nama' => 'Sidorejo', 'slug' => 'sidorejo-pagelaran', 'email' => 'desa-sidorejo-pagelaran@malangkab.go.id', 'alamat' => 'Sidorejo', 'telp' => '0341'],
            ['nama' => 'Sidorenggo', 'slug' => 'sidorenggo', 'email' => 'desa-sidorenggo@malangkab.go.id', 'alamat' => 'Jalan Raya Sidorenggo No 41', 'telp' => '0341'],
            ['nama' => 'Simojayan', 'slug' => 'simojayan', 'email' => 'desa-simojayan@malangkab.go.id', 'alamat' => 'Simojayan', 'telp' => '0341'],
            ['nama' => 'Sindurejo', 'slug' => 'sidurejo', 'email' => 'desa-sindurejo@malangkab.go.id', 'alamat' => 'Sindurejo', 'telp' => '0341'],
            ['nama' => 'Sitiarjo', 'slug' => 'sitiarjo', 'email' => 'desa-sitiarjo@malangkab.go.id', 'alamat' => 'Sitiarjo', 'telp' => '0341'],
            ['nama' => 'Sitirejo', 'slug' => 'sitirejo', 'email' => 'desa-sitirejo@malangkab.go.id', 'alamat' => 'Sitirejo', 'telp' => '0341'],
            ['nama' => 'Slamet', 'slug' => 'slamet', 'email' => 'desa-slamet@malangkab.go.id', 'alamat' => 'Slamet', 'telp' => '0341'],
            ['nama' => 'Slamparejo', 'slug' => 'slamparejo', 'email' => 'desa-slamparejo@malangkab.go.id', 'alamat' => 'Slamparejo', 'telp' => '0341'],
            ['nama' => 'Slorok', 'slug' => 'slorok', 'email' => 'desaslorok01@gmail.com', 'alamat' => 'Slorok', 'telp' => '081231637291'],
            ['nama' => 'Sonowangi', 'slug' => 'sonowangi', 'email' => 'desa-sonowangi@malangkab.go.id', 'alamat' => 'Sonowangi', 'telp' => '0341'],
            ['nama' => 'Srigading', 'slug' => 'srigading', 'email' => 'desa-srigading@malangkab.go.id', 'alamat' => 'Srigading', 'telp' => '0341'],
            ['nama' => 'Srigonco', 'slug' => 'srigonco', 'email' => 'desa-srigonco@malangkab.go.id', 'alamat' => 'Srigonco', 'telp' => '0341'],
            ['nama' => 'Srimulyo', 'slug' => 'srimulyo', 'email' => 'desa-srimulyo@malangkab.go.id', 'alamat' => 'Srimulyo', 'telp' => '0341'],
            ['nama' => 'Sudimoro', 'slug' => 'sudimoro', 'email' => 'desa-sudimoro@malangkab.go.id', 'alamat' => 'Sudimoro', 'telp' => '0341'],
            ['nama' => 'Sukoanyar', 'slug' => 'sukoanyar-pakis', 'email' => 'desa-sukoanyar-pakis@malangkab.go.id', 'alamat' => 'Sukoanyar', 'telp' => '0341'],
            ['nama' => 'Sukoanyar', 'slug' => 'sukoanyar-wajak', 'email' => 'desa-sukoanyar-wajak@malangkab.go.id', 'alamat' => 'Jalan Raya 503 Dusun Krajan', 'telp' => '0341'],
            ['nama' => 'Sukodadi', 'slug' => 'sukodadi', 'email' => 'desa-sukodadi.malangkab.go.id', 'alamat' => 'Sukodadi', 'telp' => '0341'],
            ['nama' => 'Sukolilo', 'slug' => 'sukolilo-jabung', 'email' => 'desa-sukolilo-jabung@malangkab.go.id', 'alamat' => 'Sukolilo', 'telp' => '0341'],
            ['nama' => 'Sukolilo', 'slug' => 'sukolilo-wajak', 'email' => 'desa-sukolilo-wajak@malangkab.go.id', 'alamat' => 'Sukolilo', 'telp' => '0341'],
            ['nama' => 'Sukomulyo', 'slug' => 'sukomulyo', 'email' => 'desa-sukomulyo@malangkab.go.id', 'alamat' => 'Sukomulyo', 'telp' => '0341'],
            ['nama' => 'Sukonolo', 'slug' => 'sukonolo', 'email' => 'desa-sukonolo@malangkab.go.id', 'alamat' => 'Sukonolo', 'telp' => '0341'],
            ['nama' => 'Sukopuro', 'slug' => 'sukopuro', 'email' => 'desa-sukopuro@malangkab.go.id', 'alamat' => 'Sukopuro', 'telp' => '0341788525'],
            ['nama' => 'Sukoraharjo', 'slug' => 'sukoraharjo', 'email' => 'desa-sukoraharjo@malangkab.go.id', 'alamat' => 'Sukoraharjo', 'telp' => '0341'],
            ['nama' => 'Sukorejo', 'slug' => 'sukorejo-gondanglegi', 'email' => 'PemdeSukorejo01@gmail.com', 'alamat' => 'Jl. Pahlawan No.05', 'telp' => '082334602518'],
            ['nama' => 'Sukorejo', 'slug' => 'sukorejo-tirtoyudo', 'email' => 'desa-sukorejo-tirtoyudo@malangkab.go.id', 'alamat' => 'Sukorejo', 'telp' => '0341'],
            ['nama' => 'Sukosari', 'slug' => 'sukosari-gondanglegi', 'email' => 'desa-sukosari-gondanglegi@malangkab.go.id', 'alamat' => 'Sukosari', 'telp' => '0341'],
            ['nama' => 'Sukosari', 'slug' => 'sukosari-kasembon', 'email' => 'desa-sukosari-kasembon@malangkab.go.id', 'alamat' => 'Sukosari', 'telp' => '0341'],
            ['nama' => 'Sukowilangun', 'slug' => 'sukowilangun', 'email' => 'desa-sukowilangun@malangkab.go.id', 'alamat' => 'Sukowilangun', 'telp' => '0341'],
            ['nama' => 'Sumberagung', 'slug' => 'sumberagung-ngantang', 'email' => 'desa-sumberagung-ngantang@malangkab.go.id', 'alamat' => 'Sumberagung', 'telp' => '0341'],
            ['nama' => 'Sumberagung', 'slug' => 'sumberagung-sumawe', 'email' => 'desa-sumberagung-sumbermanjingwetan@malangkab.go.id', 'alamat' => 'Sumberagung', 'telp' => '0341'],
            ['nama' => 'Sumberbening', 'slug' => 'sumberbening', 'email' => 'desa-sumberbening@malangkab.go.id', 'alamat' => 'Sumberbening', 'telp' => '0341'],
            ['nama' => 'Sumberdem', 'slug' => 'sumberdem', 'email' => 'desa-sumberdem@malangkab.go.id', 'alamat' => 'Sumberdem', 'telp' => '0341'],
            ['nama' => 'Sumberejo', 'slug' => 'sumberejo', 'email' => 'desa-sumberejo@malangkab.go.id', 'alamat' => 'Sumberejo', 'telp' => '0341'],
            ['nama' => 'Sumberejo', 'slug' => 'sumberejo-pagak', 'email' => 'desa-sumberejo-pagak@malangkab.go.id', 'alamat' => 'Sumberejo', 'telp' => '0341'],
            ['nama' => 'Sumberejo', 'slug' => 'sumberejo-poncokusumo', 'email' => 'desa-sumberejo-poncokusumo@malangkab.go.id', 'alamat' => 'Sumberejo', 'telp' => '0341'],
            ['nama' => 'Sumberjaya', 'slug' => 'sumberjaya', 'email' => 'desa-sumberjaya@malangkab.go.id', 'alamat' => 'Sumberjaya', 'telp' => '0341'],
            ['nama' => 'Sumberkerto', 'slug' => 'sumberkerto', 'email' => 'desa-sumberkerto@malangkab.go.id', 'alamat' => 'Sumberkerto', 'telp' => '0341'],
            ['nama' => 'Sumberkradenan', 'slug' => 'sumberkradenan', 'email' => 'desa-sumberkradenan@malangkab.go.id', 'alamat' => 'Sumberkradenan', 'telp' => '0341'],
            ['nama' => 'Sumbermanjing', 'slug' => 'sumbermanjing', 'email' => 'desa-sumbermanjing@malangkab.go.id', 'alamat' => 'Sumbermanjing', 'telp' => '0341'],
            ['nama' => 'Sumbermanjingkulon', 'slug' => 'sumbermanjingkulon', 'email' => 'desa-sumbermanjingkulon@malangkab.go.id', 'alamat' => 'Sumbermanjingkulon', 'telp' => '0341'],

            // --- DESA BAGIAN 8 ---
            ['nama' => 'Sumberngepoh', 'slug' => 'sumberngepoh', 'email' => 'desa-sumberngepoh@malangkab.go.id', 'alamat' => 'Sumberngepoh', 'telp' => '0341'],
            ['nama' => 'Sumberoto', 'slug' => 'sumberoto', 'email' => 'desa-sumberoto@malangkab.go.id', 'alamat' => 'Sumberoto', 'telp' => '0341'],
            ['nama' => 'Sumberpasir', 'slug' => 'sumberpasir', 'email' => 'desa-sumberpasir@malangkab.go.id', 'alamat' => 'Sumberpasir', 'telp' => '0341'],
            ['nama' => 'Sumberpetung', 'slug' => 'sumberpetung', 'email' => 'desa-sumberpetung@malangkab.go.id', 'alamat' => 'Sumberpetung', 'telp' => '0341'],
            ['nama' => 'Sumberporong', 'slug' => 'sumberporong', 'email' => 'desa-sumberporong@malangkab.go.id', 'alamat' => 'Jl. A Yani no 31 RW 01', 'telp' => '0341424266'],
            ['nama' => 'Sumberpucung', 'slug' => 'sumberpucung', 'email' => 'desa-sumberpucung@malangkab.go.id', 'alamat' => 'Jl. Jendral Sudirman No.232', 'telp' => '0341385256'],
            ['nama' => 'Sumberputih', 'slug' => 'sumberputih', 'email' => 'desa-sumberputih@malangkab.go.id', 'alamat' => 'Sumberputih', 'telp' => '0341'],
            ['nama' => 'Sumbersekar', 'slug' => 'sumbersekar', 'email' => 'desa-sumbersekar@malangkab.go.id', 'alamat' => 'Sumbersekar', 'telp' => '0341'],
            ['nama' => 'Sumbersuko', 'slug' => 'sumbersuko-dampit', 'email' => 'desa-sumbersuko-dampit@malangkab.go.id', 'alamat' => 'Sumbersuko', 'telp' => '0341'],
            ['nama' => 'Sumbersuko', 'slug' => 'sumbersuko-tajinan', 'email' => 'desa-sumbersuko-tajinan@malangkab.go.id', 'alamat' => 'Sumbersuko', 'telp' => '0341'],
            ['nama' => 'Sumbersuko', 'slug' => 'sumbersuko-wagir', 'email' => 'desa-sumbersuko-wagir@malangkab.go.id', 'alamat' => 'Sumbersuko', 'telp' => '0341'],
            ['nama' => 'sumbertangkil', 'slug' => 'sumbertangkil', 'email' => 'desa-sumbertangkil@malangkab.go.id', 'alamat' => 'umbertangkil', 'telp' => '0341'],
            ['nama' => 'Sumbertempur', 'slug' => 'sumbertempur', 'email' => 'desa-sumbertempur@malangkab.go.id', 'alamat' => 'Sumbertempur', 'telp' => '0341'],
            ['nama' => 'Sutojayan', 'slug' => 'sutojayan', 'email' => 'desa-sutojayan@malangkab.go.id', 'alamat' => 'Sutojayan', 'telp' => '0341'],
            ['nama' => 'Suwaru', 'slug' => 'sewaru', 'email' => 'desa-sewaru@malangkab.go.id', 'alamat' => 'Sewaru', 'telp' => '0341'],
            ['nama' => 'Taji', 'slug' => 'taji', 'email' => 'desa-taji@malangkab.go.id', 'alamat' => 'Taji', 'telp' => '0341'],
            ['nama' => 'Tajinan', 'slug' => 'tajinan', 'email' => 'desa-tajinan@malangkab.go.id', 'alamat' => 'Tajinan', 'telp' => '0341'],
            ['nama' => 'Talang Suko', 'slug' => 'talang-suko', 'email' => 'desa-talangsuko@malangkab.go.id', 'alamat' => 'Talang Suko', 'telp' => '0341'],
            ['nama' => 'Talangagung', 'slug' => 'talangagung', 'email' => 'desa-talangagung@malangkab.go.id', 'alamat' => 'Talangangung', 'telp' => '0341'],
            ['nama' => 'Talok', 'slug' => 'talok', 'email' => 'desa-talok@malangkab.go.id', 'alamat' => 'Talok', 'telp' => '0341'],
            ['nama' => 'Taman Kuncaran', 'slug' => 'taman-kuncaran', 'email' => 'desa-tamankuncaran@malangkab.go.id', 'alamat' => 'Taman Kuncaran', 'telp' => '0341'],
            ['nama' => 'Tamanasri', 'slug' => 'tamanasri', 'email' => 'desa-tamanasri@malangkab.go.id', 'alamat' => 'Tamanasri', 'telp' => '0341'],
            ['nama' => 'Tamanharjo', 'slug' => 'tamanharjo', 'email' => 'desa-tamanharjo@malangkab.go.id', 'alamat' => 'Tamanharjo', 'telp' => '0341'],
            ['nama' => 'Tamansari', 'slug' => 'tamansari', 'email' => 'desa-tamansari@malangkab.go.id', 'alamat' => 'Tamansari', 'telp' => '0341'],
            ['nama' => 'Tamansatriyan', 'slug' => 'tamansatriyan', 'email' => 'desa-tamansatrian@malangkab.go.id', 'alamat' => 'Jl Semeru No. 160', 'telp' => '0341'],
            ['nama' => 'TAMBAKASRI', 'slug' => 'tambakasri-sumawe', 'email' => 'desa-tambakasri-sumbermanjingwetan@malangkab.go.id', 'alamat' => 'jalan raya Sidomulyo', 'telp' => '+6281233406373'],
            ['nama' => 'Tambakasri', 'slug' => 'tambakasri-tajinan', 'email' => 'desa-tambakasri-tajinan@malangkab.go.id', 'alamat' => 'Tambakasri', 'telp' => '0341'],
            ['nama' => 'Tambakrejo', 'slug' => 'tambakrejo', 'email' => 'desa-tambakrejo@malangkab.go.id', 'alamat' => 'Tambakrejo', 'telp' => '0341'],
            ['nama' => 'Tanggung', 'slug' => 'tanggung', 'email' => 'desa-tanggung@malangkab.go.id', 'alamat' => 'Tanggung', 'telp' => '0341'],
            ['nama' => 'Tangkilsari', 'slug' => 'tangkilsari', 'email' => 'desa-tangkilsari@malangkab.go.id', 'alamat' => 'Tangkilsari', 'telp' => '0341'],
            ['nama' => 'Tawang Rejeni', 'slug' => 'tawang-rejeni', 'email' => 'desa-tawangrejeni@malangkab.go.id', 'alamat' => 'Tawang Rejeni', 'telp' => '0341'],
            ['nama' => 'Tawangagung', 'slug' => 'tawangagung', 'email' => 'desa-tawangagung@malangkab.go.id', 'alamat' => 'Tawangagung', 'telp' => '0341'],
            ['nama' => 'Tawangargo', 'slug' => 'tawangargo', 'email' => 'desa-tawangargo@malangkab.go.id', 'alamat' => 'Tawangargo', 'telp' => '0341'],
            ['nama' => 'Tawangsari', 'slug' => 'tawangsari', 'email' => 'desa-tawangsari@malangkab.go.id', 'alamat' => 'Tawangsari', 'telp' => '0341'],
            ['nama' => 'Tegalgondo', 'slug' => 'tegalgondo', 'email' => 'desa-tegalgondo@malangkab.go.id', 'alamat' => 'Tegalgondo', 'telp' => '081232574050'],
            ['nama' => 'Tegalrejo', 'slug' => 'tegalrejo', 'email' => 'desa-tegalrejo@malangkab.go.id', 'alamat' => 'Tegalrejo', 'telp' => '0341'],
            ['nama' => 'Tegalsari', 'slug' => 'tegalsari', 'email' => 'desa-tegalsari@malangkab.go.id', 'alamat' => 'Tegalsari', 'telp' => '0341'],
            ['nama' => 'Tegalweru', 'slug' => 'tegalweru', 'email' => 'desa-tegalweru@malangkab.go.id', 'alamat' => 'Tegalweru', 'telp' => '0341'],
            ['nama' => 'Tempursari', 'slug' => 'tempursari', 'email' => 'desa-tempursari@malangkab.go.id', 'alamat' => 'Tempursari', 'telp' => '0341'],
            ['nama' => 'Ternyang', 'slug' => 'ternyang', 'email' => 'desa-ternyang@malangkab.go.id', 'alamat' => 'Ternyang', 'telp' => '0341'],
            ['nama' => 'Tirtomarto', 'slug' => 'tirtomarto', 'email' => 'desa-tirtomarto@malangkab.go.id', 'alamat' => 'Tirtomarto', 'telp' => '0341'],
            ['nama' => 'Tirtomoyo', 'slug' => 'tirtomoyo-ampelgading', 'email' => 'desa-tirtomoyo-ampelgading@malangkab.go.id', 'alamat' => 'Tirtomoyo', 'telp' => '0341'],
            ['nama' => 'Tirtomoyo', 'slug' => 'tirtomoyo-pakis', 'email' => 'desa-tirtomoyo-pakis@malangkab.go.id', 'alamat' => 'Tirtomoyo', 'telp' => '0341'],
            ['nama' => 'Tirtoyudo', 'slug' => 'tirtoyudo', 'email' => 'desa-tirtoyudo@malangkab.go.id', 'alamat' => 'Tirtoyudo', 'telp' => '0341'],
            ['nama' => 'Tlogorejo', 'slug' => 'tlogorejo', 'email' => 'desa-tlogorejo@malangkab.go.id', 'alamat' => 'Tlogorejo', 'telp' => '0341'],
            ['nama' => 'Tlogosari', 'slug' => 'tlogosari-donomulyo', 'email' => 'desa-tlogosari-donomulyo@malangkab.go.id', 'alamat' => 'Tlogosari', 'telp' => '0341'],
            ['nama' => 'Tlogosari', 'slug' => 'tlogosari-tirtoyudo', 'email' => 'desa-tlogosari@malangkab.go.id', 'alamat' => 'Tlogosari', 'telp' => '0341'],
            ['nama' => 'Tulungrejo', 'slug' => 'tulungrejo-donomulyo', 'email' => 'desa-tulungrejo-donomulyo@malangkab.go.id', 'alamat' => 'Tulungrejo', 'telp' => '0341'],
            ['nama' => 'Tulungrejo', 'slug' => 'tulungrejo-ngantang', 'email' => 'desa-tulungrejo-ngantang@malangkab.go.id', 'alamat' => 'Tulungrejo', 'telp' => '0341'],
            ['nama' => 'Tulusbesar', 'slug' => 'tulusbesar', 'email' => 'desa-tulusbesar@malangkab.go.id', 'alamat' => 'Tulusbesar', 'telp' => '0341'],
            ['nama' => 'Tumpak Renteng', 'slug' => 'tumpak-renteng', 'email' => 'desa-tumpukrenteng@malangkab.go.id', 'alamat' => 'Tumpak Renteng', 'telp' => '0341'],
            ['nama' => 'Tumpakrejo', 'slug' => 'tumpakrejo-gedangan', 'email' => 'desa-tumpakrejo-gedangan@malangkab.go.id', 'alamat' => 'Tumpakrejo', 'telp' => '0341'],
            ['nama' => 'Tumpakrejo', 'slug' => 'tumpakrejo-kalipare', 'email' => 'desa-tumpakrejo-kalipare@malangkab.go.id', 'alamat' => 'Tumpakrejo', 'telp' => '0341'],
            ['nama' => 'Tumpang', 'slug' => 'tumpang', 'email' => 'desa-tumpang@malangkab.go.id', 'alamat' => 'Tumpang', 'telp' => '0341787121'],
            ['nama' => 'Tunjungtirto', 'slug' => 'tunjungtirto', 'email' => 'desa-tunjungtirto@malangkab.go.id', 'alamat' => 'Tunjungtirto', 'telp' => '0341'],
            ['nama' => 'Turirejo', 'slug' => 'turirejo', 'email' => 'desa-turirejo@malangkab.go.id', 'alamat' => 'Turirejo', 'telp' => '0341'],
            ['nama' => 'Undaan', 'slug' => 'undaan', 'email' => 'desa-undaan@malangkab.go.id', 'alamat' => 'Undaan', 'telp' => '0341'],
            ['nama' => 'Urek_Urek', 'slug' => 'urek-urek', 'email' => 'desa-urekurek@malangkab.go.id', 'alamat' => 'Urek_Urek', 'telp' => '0341'],
            ['nama' => 'Wadung', 'slug' => 'wadung', 'email' => 'desa-wadung@malangkab.go.id', 'alamat' => 'Wadung', 'telp' => '0341'],
            ['nama' => 'Wajak', 'slug' => 'wajak', 'email' => 'desa-wajak@malangkab.go.id', 'alamat' => 'Wajak', 'telp' => '0341'],
            ['nama' => 'Wandanpuro', 'slug' => 'wandanpuro', 'email' => 'desawandanpuro70@gmail.com', 'alamat' => 'Wandanpuro', 'telp' => '0341833061'],
            ['nama' => 'Watugede', 'slug' => 'watugede', 'email' => 'desa-watugede@malangkab.go.id', 'alamat' => 'Watugede', 'telp' => '0341'],
            ['nama' => 'Waturejo', 'slug' => 'waturejo', 'email' => 'desa-waturejo@malangkab.go.id', 'alamat' => 'Waturejo', 'telp' => '0341'],
            ['nama' => 'Wirotaman', 'slug' => 'wirotaman', 'email' => 'desa-wirotaman@malangkab.go.id', 'alamat' => 'Wirotaman', 'telp' => '0341'],
            ['nama' => 'Wiyurejo', 'slug' => 'wiyurejo', 'email' => 'desa-wiyurejo@malangkab.go.id', 'alamat' => 'Wiyurejo', 'telp' => '0341'],
            ['nama' => 'Wonoagung', 'slug' => 'wonoagung-kasembon', 'email' => 'desa-wonoagung-kasembon@malangkab.go.id', 'alamat' => 'Wonoagung', 'telp' => '0341'],
            ['nama' => 'Wonoagung Kecamatan', 'slug' => 'wonoagung-tirtoyudo', 'email' => 'desa-wonoagung@malangkab.go.id', 'alamat' => 'Wonoagung', 'telp' => '+6285204889499'],
            ['nama' => 'Wonoayu', 'slug' => 'wonoayu', 'email' => 'desa-wonoayu@malangkab.go.id', 'alamat' => 'Wonoayu', 'telp' => '0341'],
            ['nama' => 'Wonokerso', 'slug' => 'wonokerso', 'email' => 'desa-wonokerso@malangkab.go.id', 'alamat' => 'Wonokerso', 'telp' => '0341'],
            ['nama' => 'Wonokerto', 'slug' => 'wonokerto', 'email' => 'desa-wonokerto@malangkab.go.id', 'alamat' => 'Wonokerto', 'telp' => '082141044001'],
            ['nama' => 'Wonomulyo', 'slug' => 'wonomulyo', 'email' => 'desa-wonomulyo@malangkab.go.id', 'alamat' => 'Wonomulyo', 'telp' => '0341'],
            ['nama' => 'Wonorejo', 'slug' => 'wonorejo-bantur', 'email' => 'desa-wonorejo-bantur@malangkab.go.id', 'alamat' => 'Wonorejo', 'telp' => '0341'],
            ['nama' => 'Wonorejo', 'slug' => 'wonorejo-lawang', 'email' => 'desa-wonorejo-lawang@malangkab.go.id', 'alamat' => 'Wonorejo', 'telp' => '0341425143'],
            ['nama' => 'Wonorejo', 'slug' => 'wonorejo-poncokusumo', 'email' => 'desa-wonorejo-poncokusumo@malangkab.go.id', 'alamat' => 'Wonorejo', 'telp' => '0341'],
            ['nama' => 'Wonorejo', 'slug' => 'wonorejo-singosari', 'email' => 'desa-wonorejo-singosari@malangkab.go.id', 'alamat' => 'Wonorejo', 'telp' => '0341'],
            ['nama' => 'Wonosari', 'slug' => 'wonosari', 'email' => 'desa-wonosari@malangkab.go.id', 'alamat' => 'Wonosari', 'telp' => '0341'],
            ['nama' => 'Wringinanom', 'slug' => 'wringinanom', 'email' => 'desa-wringinanom@malangkab.go.id', 'alamat' => 'Wringinanom', 'telp' => '0341'],
            ['nama' => 'Wringinsongo', 'slug' => 'wringinsongo', 'email' => 'desa-wringinsongo@malangkab.go.id', 'alamat' => 'Wringinsongo', 'telp' => '0341'],

        ];

        foreach ($data as $item) {
            $pd = PerangkatDaerah::create([
                'nama_pd' => $item['nama'],
                'slug' => $item['slug'],
                'email' => $item['email'],
                'alamat' => $item['alamat'],
                'telepon' => $item['telp'] ?? '-',
            ]);

            User::create([
                'perangkat_daerah_id' => $pd->id,
                'name' => 'admin' . str_replace('-', '', $item['slug']),
                'email' => $item['email'] ?? ($item['slug'] . '@placeholder.com'),
                'password' => Hash::make('admin123'),
            ]);
        }
    }
}
